#!/bin/bash
# compose.sh — Assembles AGENTS.md from profile + fragments
# Called by: just compose <profile> <target>
set -euo pipefail

# ── Argument parsing ──────────────────────────────────────────────────────────
LIBRARY=""
PROFILE=""
TARGET=""
DRY_RUN=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --library)  LIBRARY="$2";  shift 2 ;;
    --profile)  PROFILE="$2";  shift 2 ;;
    --target)   TARGET="$2";   shift 2 ;;
    --dry-run)  DRY_RUN=true;  shift   ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

[[ -z "$LIBRARY" ]] && { echo "Error: --library required" >&2; exit 1; }
[[ -z "$PROFILE" ]] && { echo "Error: --profile required" >&2; exit 1; }
[[ -z "$TARGET"  ]] && { echo "Error: --target required" >&2; exit 1; }

# ── Profile resolution ────────────────────────────────────────────────────────
PROFILE_FILE="$LIBRARY/profiles/$PROFILE.yaml"
[[ ! -f "$PROFILE_FILE" ]] && {
  echo "Error: profile '$PROFILE' not found at $PROFILE_FILE" >&2
  echo "Run 'just list-profiles' to see available profiles." >&2
  exit 1
}

PROFILE_NAME=$(yq '.meta.name'        "$PROFILE_FILE")
PROFILE_VER=$(yq  '.meta.version'     "$PROFILE_FILE")
GENERATED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
PROJECT_NAME=$(basename "$TARGET")
PROJECT_HEADER=$(yq '.output.project_header // ""' "$PROFILE_FILE")
BUILD_CMD=$(yq     '.output.build_command  // ""'  "$PROFILE_FILE")
TEST_CMD=$(yq      '.output.test_command   // ""'  "$PROFILE_FILE")
LINT_CMD=$(yq      '.output.lint_command   // ""'  "$PROFILE_FILE")

# ── Fragment loading ──────────────────────────────────────────────────────────
load_fragments() {
  local group="$1"   # e.g. "base", "languages", "architecture"
  local subdir="$2"  # e.g. "agents/base", "agents/languages"

  local names=()
  while IFS= read -r _name; do
    names+=("$_name")
  done < <(yq ".fragments.${group}[]" "$PROFILE_FILE" 2>/dev/null || true)

  for name in "${names[@]+"${names[@]}"}"; do
    [[ -z "$name" || "$name" == "null" ]] && continue
    local frag_file="$LIBRARY/$subdir/$name.md"
    if [[ ! -f "$frag_file" ]]; then
      echo "Warning: fragment '$subdir/$name.md' not found — skipping" >&2
      continue
    fi
    printf '\n<!-- fragment: %s/%s -->\n\n' "$subdir" "$name"
    cat "$frag_file"
    printf '\n'
  done
}

# ── Assemble ──────────────────────────────────────────────────────────────────
OUTPUT=$(cat <<HEADER
# Agent Instructions — ${PROJECT_NAME}

<!-- AUTO-GENERATED by agentic library -->
<!-- Source profile: ${PROFILE_NAME} (v${PROFILE_VER}) -->
<!-- Generated: ${GENERATED_AT} -->
<!-- DO NOT EDIT the generated sections — run \`just compose ${PROFILE} <target>\` to regenerate -->

HEADER
)

# Project-specific header (from profile output.project_header)
if [[ -n "$PROJECT_HEADER" && "$PROJECT_HEADER" != "null" ]]; then
  OUTPUT+=$'\n'"## Project Context"$'\n\n'"${PROJECT_HEADER}"$'\n'
fi

# Commands section
if [[ -n "$BUILD_CMD" || -n "$TEST_CMD" || -n "$LINT_CMD" ]]; then
  OUTPUT+=$'\n'"## Commands"$'\n\n'
  [[ -n "$BUILD_CMD" && "$BUILD_CMD" != "null" ]] && OUTPUT+="- **Build**: \`${BUILD_CMD}\`"$'\n'
  [[ -n "$TEST_CMD"  && "$TEST_CMD"  != "null" ]] && OUTPUT+="- **Test**: \`${TEST_CMD}\`"$'\n'
  [[ -n "$LINT_CMD"  && "$LINT_CMD"  != "null" ]] && OUTPUT+="- **Lint**: \`${LINT_CMD}\`"$'\n'
fi

# Fragments in layer order
OUTPUT+=$(load_fragments "base"         "agents/base")
OUTPUT+=$(load_fragments "languages"    "agents/languages")
OUTPUT+=$(load_fragments "frameworks"   "agents/frameworks")
OUTPUT+=$(load_fragments "architecture" "agents/architecture")
OUTPUT+=$(load_fragments "practices"    "agents/practices")
OUTPUT+=$(load_fragments "domains"      "agents/domains")

# Local override (project-specific additions, if present)
LOCAL_OVERRIDE="$TARGET/AGENTS.local.md"
if [[ -f "$LOCAL_OVERRIDE" ]]; then
  OUTPUT+=$'\n<!-- local override: AGENTS.local.md -->\n\n'
  OUTPUT+=$(cat "$LOCAL_OVERRIDE")
  OUTPUT+=$'\n'
fi

# ── Output ────────────────────────────────────────────────────────────────────
if [[ "$DRY_RUN" == "true" ]]; then
  printf '%s\n' "$OUTPUT"
else
  mkdir -p "$TARGET"
  echo "$OUTPUT" > "$TARGET/AGENTS.md"

  # Write lock file
  LOCK_DIR="$TARGET/.agentic"
  mkdir -p "$LOCK_DIR"
  cat > "$LOCK_DIR/config.yaml" <<LOCK
# Managed by agentic library — do not edit manually
# Regenerate with: just compose ${PROFILE} ${TARGET}
library_commit: "$(cd "$LIBRARY" && git rev-parse HEAD 2>/dev/null || echo "unknown")"
profile: "${PROFILE}"
profile_version: "${PROFILE_VER}"
composed_at: "${GENERATED_AT}"
LOCK

  echo "Composed AGENTS.md → $TARGET/AGENTS.md"
fi
