#!/bin/bash
# init.sh — Deploy only the agentic wrapper script to a target project
# Called by: just init /path/to/project
# This is useful for existing projects that already have AGENTS.md
set -euo pipefail

# ── Argument parsing ──────────────────────────────────────────────────────────
LIBRARY=""
TARGET=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --library) LIBRARY="$2"; shift 2 ;;
    --target)  TARGET="$2";  shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

[[ -z "$LIBRARY" ]] && { echo "Error: --library required" >&2; exit 1; }
[[ -z "$TARGET"  ]] && { echo "Error: --target required" >&2; exit 1; }

# Create target if it doesn't exist
mkdir -p "$TARGET"

# Resolve absolute paths
lib_abs="$(cd "$LIBRARY" && pwd)"
target_abs="$(cd "$TARGET" && pwd)"

# ── Deploy agentic wrapper ────────────────────────────────────────────────────
wrapper="$TARGET/agentic"

cat > "$wrapper" <<'WRAPPER_HEAD'
#!/bin/bash
# Auto-generated by agentic library — do not edit manually
# Usage: ./agentic <vendor|list|sync>
set -euo pipefail

TARGET_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="$TARGET_DIR/.agentic/config.yaml"

# Resolve library path dynamically
LIBRARY=""
if [[ -f "$CONFIG" ]]; then
  LIBRARY=$(yq '.library_path // ""' "$CONFIG" 2>/dev/null || echo "")
  [[ "$LIBRARY" == "null" ]] && LIBRARY=""
fi

if [[ -z "$LIBRARY" || ! -d "$LIBRARY" ]]; then
  if [[ -n "${AGENTIC_REPO_ROOT:-}" && -d "$AGENTIC_REPO_ROOT" ]]; then
    LIBRARY="$AGENTIC_REPO_ROOT"
  fi
fi

WRAPPER_HEAD

# Add the hardcoded fallback
cat >> "$wrapper" <<WRAPPER_FALLBACK
# Fallback to original deployment location
if [[ -z "\$LIBRARY" || ! -d "\$LIBRARY" ]]; then
  LIBRARY="${lib_abs}"
fi

WRAPPER_FALLBACK

cat >> "$wrapper" <<'WRAPPER_TAIL'
# Validate library exists
if [[ ! -d "$LIBRARY" ]]; then
  echo "Error: agentic library not found" >&2
  echo "Set AGENTIC_REPO_ROOT or update library_path in .agentic/config.yaml" >&2
  exit 1
fi

VENDOR_SWITCH="$LIBRARY/tooling/lib/vendor-switch.sh"
if [[ ! -f "$VENDOR_SWITCH" ]]; then
  echo "Error: vendor-switch.sh not found at $VENDOR_SWITCH" >&2
  exit 1
fi

exec bash "$VENDOR_SWITCH" --library "$LIBRARY" --target "$TARGET_DIR" "$@"
WRAPPER_TAIL

chmod +x "$wrapper"

# ── Update .gitignore ─────────────────────────────────────────────────────────
gitignore="$TARGET/.gitignore"
gitignore_entries=(
  "# Agentic library — vendor symlinks (recreated by ./agentic <vendor>)"
  "agentic"
  "CLAUDE.md"
  "opencode.json"
  ".github/copilot-instructions.md"
  ".github/instructions/"
  ".gemini/"
  ".claude/skills"
  ".opencode/skills"
  ".agents/skills"
)

# Create .gitignore if missing, then add entries
touch "$gitignore"
for entry in "${gitignore_entries[@]}"; do
  if ! grep -qxF "$entry" "$gitignore" 2>/dev/null; then
    echo "$entry" >> "$gitignore"
  fi
done

# ── Create minimal config if missing ──────────────────────────────────────────
config_dir="$TARGET/.agentic"
config_file="$config_dir/config.yaml"

if [[ ! -f "$config_file" ]]; then
  mkdir -p "$config_dir"
  cat > "$config_file" <<CONFIG
# Managed by agentic library
library_path: "${lib_abs}"
active_vendors: []
CONFIG
  echo "Created: .agentic/config.yaml"
fi

echo "Deployed: ./agentic wrapper"
echo ""
echo "Usage:"
echo "  ./agentic claude          # Activate Claude vendor"
echo "  ./agentic claude,copilot  # Activate multiple vendors"
echo "  ./agentic list            # List available vendors"
echo "  ./agentic sync            # Regenerate from library"
