#!/bin/bash
# test.sh — Integration test suite for the agentic library tooling
# Called by: just test
set -euo pipefail

# ── Argument parsing ──────────────────────────────────────────────────────────
LIBRARY=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --library) LIBRARY="$2"; shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

[[ -z "$LIBRARY" ]] && { echo "Error: --library required" >&2; exit 1; }

# ── Setup ─────────────────────────────────────────────────────────────────────
COMPOSE="$LIBRARY/tooling/lib/compose.sh"
VALIDATE="$LIBRARY/tooling/lib/validate.sh"
VENDOR_GEN="$LIBRARY/tooling/lib/vendor-gen.sh"
DEPLOY_SKILLS="$LIBRARY/tooling/lib/deploy-skills.sh"
LINT="$LIBRARY/tooling/lib/lint.sh"
INDEX="$LIBRARY/tooling/lib/index.sh"

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

PASS=0
FAIL=0

# ── Test helpers ──────────────────────────────────────────────────────────────
pass() { echo "  [PASS] $*"; PASS=$((PASS + 1)); }
fail() { echo "  [FAIL] $*"; FAIL=$((FAIL + 1)); }

assert_file_exists() {
  local file="$1" label="$2"
  if [[ -f "$file" ]]; then
    pass "$label — file exists: $file"
  else
    fail "$label — expected file does not exist: $file"
  fi
}

assert_file_not_exists() {
  local file="$1" label="$2"
  if [[ ! -e "$file" ]]; then
    pass "$label — path does not exist (as expected): $file"
  else
    fail "$label — path should not exist but does: $file"
  fi
}

assert_file_contains() {
  local file="$1" pattern="$2" label="$3"
  if grep -qF "$pattern" "$file" 2>/dev/null; then
    pass "$label — contains: $pattern"
  else
    fail "$label — missing pattern in $file: $pattern"
  fi
}

assert_file_not_contains() {
  local file="$1" pattern="$2" label="$3"
  if ! grep -qF "$pattern" "$file" 2>/dev/null; then
    pass "$label — does not contain: $pattern"
  else
    fail "$label — unexpected pattern found in $file: $pattern"
  fi
}

assert_exit_code() {
  local expected="$1" actual="$2" label="$3"
  if [[ "$actual" -eq "$expected" ]]; then
    pass "$label — exit code $expected"
  else
    fail "$label — expected exit code $expected, got $actual"
  fi
}

assert_stdout_contains() {
  local output="$1" pattern="$2" label="$3"
  if echo "$output" | grep -qF "$pattern"; then
    pass "$label — stdout contains: $pattern"
  else
    fail "$label — stdout missing: $pattern"
  fi
}

assert_json_valid() {
  local file="$1" label="$2"
  if jq . "$file" > /dev/null 2>&1; then
    pass "$label — valid JSON: $file"
  else
    fail "$label — invalid JSON: $file"
  fi
}

assert_json_min_count() {
  local file="$1" jq_expr="$2" min="$3" label="$4"
  local count
  count=$(jq "$jq_expr" "$file" 2>/dev/null || echo 0)
  if [[ "$count" -ge "$min" ]]; then
    pass "$label — count $count >= $min"
  else
    fail "$label — count $count < $min (in $file)"
  fi
}

run_test() {
  local name="$1"
  echo ""
  echo "── $name"
}

# ── Tests ─────────────────────────────────────────────────────────────────────

# T01 — compose: typescript-hexagonal-microservice (lean default)
run_test "T01 — compose: typescript-hexagonal-microservice (lean)"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-microservice \
  --target "$TMP/t01" \
  > /dev/null 2>&1

assert_file_exists "$TMP/t01/AGENTS.md" "T01"
assert_file_contains "$TMP/t01/AGENTS.md" "<!-- AUTO-GENERATED by agentic library -->" "T01"
assert_file_contains "$TMP/t01/AGENTS.md" "## Conventions & Patterns" "T01"
assert_file_contains "$TMP/t01/AGENTS.md" ".agentic/fragments/git-conventions.md" "T01"
assert_file_contains "$TMP/t01/AGENTS.md" ".agentic/fragments/typescript.md" "T01"
assert_file_not_contains "$TMP/t01/AGENTS.md" "Conventional Commits" "T01"
assert_file_exists "$TMP/t01/.agentic/config.yaml" "T01"

# T02 — compose: go-hexagonal-microservice (lean default)
run_test "T02 — compose: go-hexagonal-microservice (lean)"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile go-hexagonal-microservice \
  --target "$TMP/t02" \
  > /dev/null 2>&1

assert_file_contains "$TMP/t02/AGENTS.md" ".agentic/fragments/go.md" "T02"
assert_file_not_contains "$TMP/t02/AGENTS.md" ".agentic/fragments/typescript.md" "T02"
assert_file_not_contains "$TMP/t02/AGENTS.md" "explicit error handling" "T02"

# T03 — compose: dry-run produces stdout, no files written
run_test "T03 — compose: dry-run produces stdout, no files written"
DRY_TMPFILE=$(mktemp "$TMP/dry-XXXXXX")
T03_EXIT=0
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-microservice \
  --target "$TMP/t03" \
  --dry-run > "$DRY_TMPFILE" 2>/dev/null || T03_EXIT=$?

assert_exit_code 0 "$T03_EXIT" "T03"
assert_file_not_exists "$TMP/t03" "T03"
assert_file_contains "$DRY_TMPFILE" "## Conventions & Patterns" "T03"

# T04 — compose: unknown profile fails with exit code 1
run_test "T04 — compose: unknown profile fails"
T04_EXIT=0
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile nonexistent-profile \
  --target "$TMP/t04" \
  > /dev/null 2>&1 || T04_EXIT=$?

assert_exit_code 1 "$T04_EXIT" "T04"

# T05 — validate: passes on correctly composed output
run_test "T05 — validate: passes on correctly composed output"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-microservice \
  --target "$TMP/t05" \
  > /dev/null 2>&1

T05_EXIT=0
bash "$VALIDATE" \
  --library "$LIBRARY" \
  --target "$TMP/t05" \
  > /dev/null 2>&1 || T05_EXIT=$?

assert_exit_code 0 "$T05_EXIT" "T05"

# T06 — validate: fails when AGENTS.md is missing
run_test "T06 — validate: fails when AGENTS.md is missing"
mkdir -p "$TMP/t06-empty"
T06_EXIT=0
bash "$VALIDATE" \
  --library "$LIBRARY" \
  --target "$TMP/t06-empty" \
  > /dev/null 2>&1 || T06_EXIT=$?

assert_exit_code 1 "$T06_EXIT" "T06"

# T07 — validate: fails when AGENTS.md has unfilled tokens
run_test "T07 — validate: fails when AGENTS.md has unfilled tokens"
mkdir -p "$TMP/t07"
cat > "$TMP/t07/AGENTS.md" <<'EOF'
# Agent Instructions — test-project

<!-- AUTO-GENERATED by agentic library -->

## Git Conventions

Follow conventional commits.

## Project Setup

Project owner: {{UNFILLED_TOKEN}}
EOF

T07_EXIT=0
bash "$VALIDATE" \
  --library "$LIBRARY" \
  --target "$TMP/t07" \
  > /dev/null 2>&1 || T07_EXIT=$?

assert_exit_code 1 "$T07_EXIT" "T07"

# T08 — vendor-gen: claude creates CLAUDE.md
run_test "T08 — vendor-gen: claude creates CLAUDE.md"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-microservice \
  --target "$TMP/t08" \
  > /dev/null 2>&1

bash "$VENDOR_GEN" \
  --library "$LIBRARY" \
  --target "$TMP/t08" \
  --vendors claude \
  > /dev/null 2>&1

assert_file_exists "$TMP/t08/CLAUDE.md" "T08"

# T09 — vendor-gen: copilot creates copilot-instructions.md
run_test "T09 — vendor-gen: copilot creates copilot-instructions.md"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-microservice \
  --target "$TMP/t09" \
  > /dev/null 2>&1

bash "$VENDOR_GEN" \
  --library "$LIBRARY" \
  --target "$TMP/t09" \
  --vendors copilot \
  > /dev/null 2>&1

assert_file_exists "$TMP/t09/.github/copilot-instructions.md" "T09"

# T10 — vendor-gen: gemini creates systemPrompt.md
run_test "T10 — vendor-gen: gemini creates systemPrompt.md"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-microservice \
  --target "$TMP/t10" \
  > /dev/null 2>&1

bash "$VENDOR_GEN" \
  --library "$LIBRARY" \
  --target "$TMP/t10" \
  --vendors gemini \
  > /dev/null 2>&1

assert_file_exists "$TMP/t10/.gemini/systemPrompt.md" "T10"

# T11 — vendor-gen: fails without AGENTS.md
run_test "T11 — vendor-gen: fails without AGENTS.md"
mkdir -p "$TMP/t11-empty"
T11_EXIT=0
bash "$VENDOR_GEN" \
  --library "$LIBRARY" \
  --target "$TMP/t11-empty" \
  --vendors claude \
  > /dev/null 2>&1 || T11_EXIT=$?

assert_exit_code 1 "$T11_EXIT" "T11"

# T12 — deploy-skills: all skills deployed
run_test "T12 — deploy-skills: all skills deployed to .claude/skills/"
mkdir -p "$TMP/t12"
bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t12" \
  --skills all \
  > /dev/null 2>&1

assert_file_exists "$TMP/t12/.claude/skills/code-review/SKILL.md" "T12"
assert_file_exists "$TMP/t12/.claude/skills/add-tests/SKILL.md" "T12"

# T13 — deploy-skills: selective deployment
run_test "T13 — deploy-skills: selective deployment"
mkdir -p "$TMP/t13"
bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t13" \
  --skills code-review,write-adr \
  > /dev/null 2>&1

assert_file_exists "$TMP/t13/.claude/skills/code-review/SKILL.md" "T13"
assert_file_exists "$TMP/t13/.claude/skills/write-adr/SKILL.md" "T13"
assert_file_not_exists "$TMP/t13/.claude/skills/fix-bug" "T13"

# T14 — lint: passes on the library itself
run_test "T14 — lint: passes on the library itself"
T14_EXIT=0
bash "$LINT" \
  --library "$LIBRARY" \
  > /dev/null 2>&1 || T14_EXIT=$?

assert_exit_code 0 "$T14_EXIT" "T14"

# T15 — index: produces valid JSON with expected counts
run_test "T15 — index: produces valid JSON"
bash "$INDEX" \
  --library "$LIBRARY" \
  > /dev/null 2>&1

assert_json_valid "$LIBRARY/index/skills.json" "T15"
assert_json_valid "$LIBRARY/index/fragments.json" "T15"
assert_json_min_count "$LIBRARY/index/skills.json" '.skills | length' 10 "T15 skills"
assert_json_min_count "$LIBRARY/index/fragments.json" '.fragments | length' 19 "T15 fragments"

# T16 — compose: profile with tech_stack produces ## Technical Stack section
run_test "T16 — compose: tech_stack profile produces ## Technical Stack"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t16" \
  > /dev/null 2>&1

assert_file_contains "$TMP/t16/AGENTS.md" "## Technical Stack" "T16"
assert_file_contains "$TMP/t16/AGENTS.md" "Go 1.23+" "T16"
assert_file_contains "$TMP/t16/AGENTS.md" "Cobra + Viper" "T16"

# T17 — compose: profile with skills produces slim ## Skills listing
run_test "T17 — compose: skills profile produces ## Skills listing"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t17" \
  > /dev/null 2>&1

assert_file_contains "$TMP/t17/AGENTS.md" "## Skills" "T17"
assert_file_contains "$TMP/t17/AGENTS.md" "Load the relevant skill file before starting the task." "T17"
assert_file_contains "$TMP/t17/AGENTS.md" "code-review" "T17"
assert_file_contains "$TMP/t17/AGENTS.md" "write-adr" "T17"

# T18 — compose: --full writes AGENTS.md with inline fragment content
run_test "T18 — compose: --full inlines fragments into AGENTS.md"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t18" \
  --full \
  > /dev/null 2>&1

assert_file_exists "$TMP/t18/AGENTS.md" "T18"
assert_file_contains "$TMP/t18/AGENTS.md" "## Git Conventions" "T18"
assert_file_contains "$TMP/t18/AGENTS.md" "## Go" "T18"
assert_file_exists "$TMP/t18/.agentic/config.yaml" "T18"
assert_file_not_exists "$TMP/t18/.agentic/fragments" "T18"

# T19 — compose: --full embeds skill content inline (not just listing)
run_test "T19 — compose: --full embeds full skill content"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t19" \
  --full \
  > /dev/null 2>&1

assert_file_contains "$TMP/t19/AGENTS.md" "## Skills" "T19"
assert_file_contains "$TMP/t19/AGENTS.md" "## Code Review Skill" "T19"
assert_file_not_contains "$TMP/t19/AGENTS.md" "Load the relevant skill file before starting the task." "T19"

# T20 — compose: profile without tech_stack/skills has no ## Technical Stack or ## Skills
run_test "T20 — compose: profile without tech_stack/skills omits those sections"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile go-hexagonal-microservice \
  --target "$TMP/t20" \
  > /dev/null 2>&1

assert_file_not_contains "$TMP/t20/AGENTS.md" "## Technical Stack" "T20"
assert_file_not_contains "$TMP/t20/AGENTS.md" "## Skills" "T20"

# T21 — compose: --full produces monolithic AGENTS.md with mode: full in lock file
run_test "T21 — compose: --full flag produces monolithic AGENTS.md"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t21" \
  --full \
  > /dev/null 2>&1

assert_file_exists "$TMP/t21/AGENTS.md" "T21"
assert_file_contains "$TMP/t21/AGENTS.md" "## Git Conventions" "T21"
assert_file_exists "$TMP/t21/.agentic/config.yaml" "T21"
assert_file_contains "$TMP/t21/.agentic/config.yaml" "mode: full" "T21"
assert_file_not_exists "$TMP/t21/.agentic/fragments" "T21"

# T22 — compose: lean default copies fragment files to target
run_test "T22 — compose: lean mode copies fragment files to .agentic/fragments/"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t22" \
  > /dev/null 2>&1

assert_file_exists "$TMP/t22/.agentic/fragments/git-conventions.md" "T22"
assert_file_exists "$TMP/t22/.agentic/fragments/go.md" "T22"
assert_file_exists "$TMP/t22/.agentic/fragments/cobra.md" "T22"
assert_file_contains "$TMP/t22/.agentic/config.yaml" "mode: lean" "T22"

# T23 — vendor-gen: copilot instructions are fully populated in lean mode
run_test "T23 — vendor-gen: copilot instructions contain fragment content in lean mode"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t23" \
  > /dev/null 2>&1

bash "$VENDOR_GEN" \
  --library "$LIBRARY" \
  --target "$TMP/t23" \
  --vendors copilot \
  > /dev/null 2>&1

assert_file_exists "$TMP/t23/.github/copilot-instructions.md" "T23"
assert_file_contains "$TMP/t23/.github/copilot-instructions.md" "Conventional Commits" "T23"
assert_file_contains "$TMP/t23/.github/copilot-instructions.md" "Git Conventions" "T23"

# T24 — compose: nested mode produces root AGENTS.md with tier table
run_test "T24 — compose: nested mode root AGENTS.md has Tiers section"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-nuxt-vite-ui \
  --target "$TMP/t24" > /dev/null 2>&1

assert_file_exists        "$TMP/t24/AGENTS.md"                                          "T24"
assert_file_contains      "$TMP/t24/AGENTS.md" "## Conventions & Patterns"              "T24"
assert_file_contains      "$TMP/t24/AGENTS.md" "## Tiers"                               "T24"
assert_file_contains      "$TMP/t24/AGENTS.md" "backend/AGENTS.md"                      "T24"
assert_file_contains      "$TMP/t24/AGENTS.md" "ui/AGENTS.md"                           "T24"
assert_file_contains      "$TMP/t24/AGENTS.md" ".agentic/fragments/tdd.md"              "T24"
assert_file_not_contains  "$TMP/t24/AGENTS.md" ".agentic/fragments/hexagonal.md"        "T24"
assert_file_not_contains  "$TMP/t24/AGENTS.md" ".agentic/fragments/vue.md"              "T24"
assert_file_contains      "$TMP/t24/.agentic/config.yaml" "structure: nested"           "T24"
assert_file_contains      "$TMP/t24/.agentic/config.yaml" "mode: lean"                  "T24"

# T25 — compose: nested lean mode writes correct tier AGENTS.md files
run_test "T25 — compose: nested lean mode tier AGENTS.md content"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-nuxt-vite-ui \
  --target "$TMP/t25" > /dev/null 2>&1

assert_file_exists        "$TMP/t25/backend/AGENTS.md"                                  "T25"
assert_file_exists        "$TMP/t25/ui/AGENTS.md"                                       "T25"
assert_file_contains      "$TMP/t25/backend/AGENTS.md" ".agentic/fragments/typescript.md"  "T25"
assert_file_contains      "$TMP/t25/backend/AGENTS.md" ".agentic/fragments/hexagonal.md"   "T25"
assert_file_not_contains  "$TMP/t25/backend/AGENTS.md" ".agentic/fragments/vue.md"         "T25"
assert_file_not_contains  "$TMP/t25/backend/AGENTS.md" ".agentic/fragments/nuxt.md"        "T25"
assert_file_contains      "$TMP/t25/ui/AGENTS.md"      ".agentic/fragments/vue.md"         "T25"
assert_file_contains      "$TMP/t25/ui/AGENTS.md"      ".agentic/fragments/nuxt.md"        "T25"
assert_file_not_contains  "$TMP/t25/ui/AGENTS.md"      ".agentic/fragments/hexagonal.md"   "T25"
assert_file_not_contains  "$TMP/t25/backend/AGENTS.md" ".agentic/fragments/tdd.md"         "T25"
assert_file_not_contains  "$TMP/t25/ui/AGENTS.md"      ".agentic/fragments/tdd.md"         "T25"
assert_file_exists        "$TMP/t25/.agentic/fragments/hexagonal.md"                    "T25"
assert_file_exists        "$TMP/t25/.agentic/fragments/vue.md"                          "T25"

# T26 — compose: nested --full inlines content into tier AGENTS.md files
run_test "T26 — compose: nested --full inlines fragment content in tier files"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-nuxt-vite-ui \
  --target "$TMP/t26" \
  --full > /dev/null 2>&1

assert_file_contains      "$TMP/t26/AGENTS.md"         "## Testing Philosophy"          "T26"
assert_file_not_contains  "$TMP/t26/AGENTS.md"         "## Hexagonal Architecture"      "T26"
assert_file_not_contains  "$TMP/t26/AGENTS.md"         "## Vue 3"                       "T26"
assert_file_contains      "$TMP/t26/backend/AGENTS.md" "## TypeScript"                  "T26"
assert_file_contains      "$TMP/t26/backend/AGENTS.md" "## Hexagonal Architecture"      "T26"
assert_file_not_contains  "$TMP/t26/backend/AGENTS.md" "## Vue 3"                       "T26"
assert_file_contains      "$TMP/t26/ui/AGENTS.md"      "## Vue 3"                       "T26"
assert_file_not_contains  "$TMP/t26/ui/AGENTS.md"      "## Hexagonal Architecture"      "T26"
assert_file_contains      "$TMP/t26/.agentic/config.yaml" "structure: nested"           "T26"

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "────────────────────────────────────────"
TOTAL=$((PASS + FAIL))
echo "Results: $PASS/$TOTAL passed"
if [[ "$FAIL" -gt 0 ]]; then
  echo "FAILED: $FAIL test(s)"
  exit 1
else
  echo "All tests passed."
fi
