#!/usr/bin/env bash
# test.sh — Integration test suite for the agentic library tooling
# Called by: just test
set -euo pipefail

# ── Argument parsing ──────────────────────────────────────────────────────────
LIBRARY=""
FILTER=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --library) LIBRARY="$2"; shift 2 ;;
    --filter) FILTER="$2"; shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

[[ -z "$LIBRARY" ]] && { echo "Error: --library required" >&2; exit 1; }

# ── Setup ─────────────────────────────────────────────────────────────────────
COMPOSE="$LIBRARY/tooling/lib/compose.sh"
VALIDATE="$LIBRARY/tooling/lib/validate.sh"
VENDOR_GEN="$LIBRARY/tooling/lib/vendor-gen.sh"
VENDOR_SWITCH="$LIBRARY/tooling/lib/vendor-switch.sh"
DEPLOY_SKILLS="$LIBRARY/tooling/lib/deploy-skills.sh"
LINT="$LIBRARY/tooling/lib/lint.sh"
INDEX="$LIBRARY/tooling/lib/index.sh"

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

PASS=0
FAIL=0

# ── Test helpers ──────────────────────────────────────────────────────────────
pass() { echo "  [PASS] $*"; PASS=$((PASS + 1)); }
fail() { echo "  [FAIL] $*"; FAIL=$((FAIL + 1)); }

assert_file_exists() {
  local file="$1" label="$2"
  if [[ -f "$file" ]]; then
    pass "$label — file exists: $file"
  else
    fail "$label — expected file does not exist: $file"
  fi
}

assert_file_not_exists() {
  local file="$1" label="$2"
  if [[ ! -e "$file" ]]; then
    pass "$label — path does not exist (as expected): $file"
  else
    fail "$label — path should not exist but does: $file"
  fi
}

assert_file_contains() {
  local file="$1" pattern="$2" label="$3"
  if grep -qF "$pattern" "$file" 2>/dev/null; then
    pass "$label — contains: $pattern"
  else
    fail "$label — missing pattern in $file: $pattern"
  fi
}

assert_file_not_contains() {
  local file="$1" pattern="$2" label="$3"
  if ! grep -qF "$pattern" "$file" 2>/dev/null; then
    pass "$label — does not contain: $pattern"
  else
    fail "$label — unexpected pattern found in $file: $pattern"
  fi
}

assert_exit_code() {
  local expected="$1" actual="$2" label="$3"
  if [[ "$actual" -eq "$expected" ]]; then
    pass "$label — exit code $expected"
  else
    fail "$label — expected exit code $expected, got $actual"
  fi
}

assert_stdout_contains() {
  local output="$1" pattern="$2" label="$3"
  if echo "$output" | grep -qF -- "$pattern"; then
    pass "$label — stdout contains: $pattern"
  else
    fail "$label — stdout missing: $pattern"
  fi
}

assert_json_valid() {
  local file="$1" label="$2"
  if jq . "$file" > /dev/null 2>&1; then
    pass "$label — valid JSON: $file"
  else
    fail "$label — invalid JSON: $file"
  fi
}

assert_json_min_count() {
  local file="$1" jq_expr="$2" min="$3" label="$4"
  local count
  count=$(jq "$jq_expr" "$file" 2>/dev/null || echo 0)
  if [[ "$count" -ge "$min" ]]; then
    pass "$label — count $count >= $min"
  else
    fail "$label — count $count < $min (in $file)"
  fi
}

assert_symlink_exists() {
  local path="$1" label="$2"
  if [[ -L "$path" ]]; then
    pass "$label — symlink exists: $path"
  else
    fail "$label — expected symlink but does not exist: $path"
  fi
}

assert_not_symlink() {
  local path="$1" label="$2"
  if [[ ! -L "$path" ]]; then
    pass "$label — not a symlink: $path"
  else
    fail "$label — expected not a symlink but is: $path"
  fi
}

run_test() {
  local name="$1"
  # Extract just the number part (e.g., "02" from "T02 — compose: ...")
  local num
  if [[ "$name" =~ T([0-9]+) ]]; then
    num="${BASH_REMATCH[1]}"
  else
    num="0"
  fi
  # Remove leading zeros to avoid octal interpretation
  num=$((10#$num))
  
  local tag="compose"
  if (( num >= 8 && num <= 13 )) || (( num >= 28 && num <= 43 )) || (( num >= 42 && num <= 43 )); then
    tag="vendor"
  elif (( num == 14 )) || (( num == 73 )); then
    tag="lint"
  elif (( num == 15 )) || (( num == 58 )) || (( num == 59 )); then
    tag="index"
  elif (( num >= 35 && num <= 38 )); then
    tag="sync"
  elif (( num >= 67 && num <= 72 )); then
    tag="mcp"
  fi

  # Skip test execution if FILTER set and tag doesn't match
  if [[ -n "$FILTER" && "$tag" != "$FILTER" ]]; then
    return
  fi
  echo ""
  echo "── $name"
}

# ── Tests ─────────────────────────────────────────────────────────────────────

# T01 — compose: typescript-hexagonal-microservice (lean default)
run_test "T01 — compose: typescript-hexagonal-microservice (lean)"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-microservice \
  --target "$TMP/t01" \
  > /dev/null 2>&1

assert_file_exists "$TMP/t01/AGENTS.md" "T01"
assert_file_contains "$TMP/t01/AGENTS.md" "<!-- AUTO-GENERATED by agentic library -->" "T01"
assert_file_contains "$TMP/t01/AGENTS.md" "## Conventions & Patterns" "T01"
assert_file_contains "$TMP/t01/AGENTS.md" ".agentic/fragments/git-conventions.md" "T01"
assert_file_contains "$TMP/t01/AGENTS.md" ".agentic/fragments/typescript.md" "T01"
assert_file_not_contains "$TMP/t01/AGENTS.md" "Conventional Commits" "T01"
assert_file_exists "$TMP/t01/.agentic/config.yaml" "T01"

# T02 — compose: go-hexagonal-microservice (lean default)
run_test "T02 — compose: go-hexagonal-microservice (lean)"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile go-hexagonal-microservice \
  --target "$TMP/t02" \
  > /dev/null 2>&1

assert_file_contains "$TMP/t02/AGENTS.md" ".agentic/fragments/go.md" "T02"
assert_file_not_contains "$TMP/t02/AGENTS.md" ".agentic/fragments/typescript.md" "T02"
assert_file_not_contains "$TMP/t02/AGENTS.md" "explicit error handling" "T02"

# T03 — compose: dry-run produces stdout, no files written
run_test "T03 — compose: dry-run produces stdout, no files written"
DRY_TMPFILE=$(mktemp "$TMP/dry-XXXXXX")
T03_EXIT=0
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-microservice \
  --target "$TMP/t03" \
  --dry-run > "$DRY_TMPFILE" 2>/dev/null || T03_EXIT=$?

assert_exit_code 0 "$T03_EXIT" "T03"
assert_file_not_exists "$TMP/t03" "T03"
assert_file_contains "$DRY_TMPFILE" "## Conventions & Patterns" "T03"

# T04 — compose: unknown profile fails with exit code 1
run_test "T04 — compose: unknown profile fails"
T04_EXIT=0
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile nonexistent-profile \
  --target "$TMP/t04" \
  > /dev/null 2>&1 || T04_EXIT=$?

assert_exit_code 1 "$T04_EXIT" "T04"

# T05 — validate: passes on correctly composed output
run_test "T05 — validate: passes on correctly composed output"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-microservice \
  --target "$TMP/t05" \
  > /dev/null 2>&1

T05_EXIT=0
bash "$VALIDATE" \
  --library "$LIBRARY" \
  --target "$TMP/t05" \
  > /dev/null 2>&1 || T05_EXIT=$?

assert_exit_code 0 "$T05_EXIT" "T05"

# T06 — validate: fails when AGENTS.md is missing
run_test "T06 — validate: fails when AGENTS.md is missing"
mkdir -p "$TMP/t06-empty"
T06_EXIT=0
bash "$VALIDATE" \
  --library "$LIBRARY" \
  --target "$TMP/t06-empty" \
  > /dev/null 2>&1 || T06_EXIT=$?

assert_exit_code 1 "$T06_EXIT" "T06"

# T07 — validate: fails when AGENTS.md has unfilled tokens
run_test "T07 — validate: fails when AGENTS.md has unfilled tokens"
mkdir -p "$TMP/t07"
cat > "$TMP/t07/AGENTS.md" <<'EOF'
# Agent Instructions — test-project

<!-- AUTO-GENERATED by agentic library -->

## Git Conventions

Follow conventional commits.

## Project Setup

Project owner: {{UNFILLED_TOKEN}}
EOF

T07_EXIT=0
bash "$VALIDATE" \
  --library "$LIBRARY" \
  --target "$TMP/t07" \
  > /dev/null 2>&1 || T07_EXIT=$?

assert_exit_code 1 "$T07_EXIT" "T07"

# T08 — vendor-gen: claude creates CLAUDE.md in vendor-files
run_test "T08 — vendor-gen: claude creates CLAUDE.md in vendor-files"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-microservice \
  --target "$TMP/t08" \
  > /dev/null 2>&1

bash "$VENDOR_GEN" \
  --library "$LIBRARY" \
  --target "$TMP/t08" \
  --vendors claude \
  > /dev/null 2>&1

assert_file_exists "$TMP/t08/.agentic/vendor-files/claude/CLAUDE.md" "T08"

# T09 — vendor-gen: copilot creates copilot-instructions.md in vendor-files
run_test "T09 — vendor-gen: copilot creates copilot-instructions.md in vendor-files"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-microservice \
  --target "$TMP/t09" \
  > /dev/null 2>&1

bash "$VENDOR_GEN" \
  --library "$LIBRARY" \
  --target "$TMP/t09" \
  --vendors copilot \
  > /dev/null 2>&1

assert_file_exists "$TMP/t09/.agentic/vendor-files/copilot/copilot-instructions.md" "T09"

# T10 — vendor-gen: gemini creates GEMINI.md in vendor-files
run_test "T10 — vendor-gen: gemini creates GEMINI.md and system.md in vendor-files"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-microservice \
  --target "$TMP/t10" \
  > /dev/null 2>&1

bash "$VENDOR_GEN" \
  --library "$LIBRARY" \
  --target "$TMP/t10" \
  --vendors gemini \
  > /dev/null 2>&1

assert_file_exists "$TMP/t10/.agentic/vendor-files/gemini/GEMINI.md" "T10 GEMINI.md"
assert_file_exists "$TMP/t10/.agentic/vendor-files/gemini/system.md" "T10 system.md"

# T11 — vendor-gen: fails without AGENTS.md
run_test "T11 — vendor-gen: fails without AGENTS.md"
mkdir -p "$TMP/t11-empty"
T11_EXIT=0
bash "$VENDOR_GEN" \
  --library "$LIBRARY" \
  --target "$TMP/t11-empty" \
  --vendors claude \
  > /dev/null 2>&1 || T11_EXIT=$?

assert_exit_code 1 "$T11_EXIT" "T11"

# T12 — deploy-skills: all skills deployed to canonical .agentic/skills/
run_test "T12 — deploy-skills: all skills deployed to .agentic/skills/"
mkdir -p "$TMP/t12"
bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t12" \
  --skills all \
  > /dev/null 2>&1

assert_file_exists "$TMP/t12/.agentic/skills/code-review/SKILL.md" "T12"
assert_file_exists "$TMP/t12/.agentic/skills/add-tests/SKILL.md" "T12"
assert_file_exists "$TMP/t12/.agentic/skills/README.md" "T12"

# T13 — deploy-skills: selective deployment to .agentic/skills/
run_test "T13 — deploy-skills: selective deployment"
mkdir -p "$TMP/t13"
bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t13" \
  --skills code-review,write-adr \
  > /dev/null 2>&1

assert_file_exists "$TMP/t13/.agentic/skills/code-review/SKILL.md" "T13"
assert_file_exists "$TMP/t13/.agentic/skills/write-adr/SKILL.md" "T13"
assert_file_not_exists "$TMP/t13/.agentic/skills/fix-bug" "T13"

# T14 — lint: passes on the library itself
run_test "T14 — lint: passes on the library itself"
T14_EXIT=0
bash "$LINT" \
  --library "$LIBRARY" \
  > /dev/null 2>&1 || T14_EXIT=$?

assert_exit_code 0 "$T14_EXIT" "T14"

# T15 — index: produces valid JSON with expected counts
run_test "T15 — index: produces valid JSON"
bash "$INDEX" \
  --library "$LIBRARY" \
  > /dev/null 2>&1

assert_json_valid "$LIBRARY/index/skills.json" "T15"
assert_json_valid "$LIBRARY/index/fragments.json" "T15"
assert_json_min_count "$LIBRARY/index/skills.json" '.skills | length' 10 "T15 skills"
assert_json_min_count "$LIBRARY/index/fragments.json" '.fragments | length' 19 "T15 fragments"

# T16 — compose: profile with tech_stack produces ## Technical Stack section
run_test "T16 — compose: tech_stack profile produces ## Technical Stack"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t16" \
  > /dev/null 2>&1

assert_file_contains "$TMP/t16/AGENTS.md" "## Technical Stack" "T16"
assert_file_contains "$TMP/t16/AGENTS.md" "Go 1.23+" "T16"
assert_file_contains "$TMP/t16/AGENTS.md" "Cobra + Viper" "T16"

# T17 — compose: profile with skills produces slim ## Skills listing
run_test "T17 — compose: skills profile produces ## Skills listing"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t17" \
  > /dev/null 2>&1

assert_file_contains "$TMP/t17/AGENTS.md" "## Skills" "T17"
assert_file_contains "$TMP/t17/AGENTS.md" "Load the relevant skill file before starting the task." "T17"
assert_file_contains "$TMP/t17/AGENTS.md" "code-review" "T17"
assert_file_contains "$TMP/t17/AGENTS.md" "write-adr" "T17"

# T18 — compose: --full writes AGENTS.md with inline fragment content
run_test "T18 — compose: --full inlines fragments into AGENTS.md"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t18" \
  --full \
  > /dev/null 2>&1

assert_file_exists "$TMP/t18/AGENTS.md" "T18"
assert_file_contains "$TMP/t18/AGENTS.md" "## Git Conventions" "T18"
assert_file_contains "$TMP/t18/AGENTS.md" "## Go" "T18"
assert_file_exists "$TMP/t18/.agentic/config.yaml" "T18"
assert_file_not_exists "$TMP/t18/.agentic/fragments" "T18"

# T19 — compose: --full embeds skill content inline (not just listing)
run_test "T19 — compose: --full embeds full skill content"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t19" \
  --full \
  > /dev/null 2>&1

assert_file_contains "$TMP/t19/AGENTS.md" "## Skills" "T19"
assert_file_contains "$TMP/t19/AGENTS.md" "## Code Review Skill" "T19"
assert_file_not_contains "$TMP/t19/AGENTS.md" "Load the relevant skill file before starting the task." "T19"

# T20 — compose: profile without tech_stack has no ## Technical Stack; has ## Skills with relational-database-design
run_test "T20 — compose: profile without tech_stack omits that section; skills section present"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile go-hexagonal-microservice \
  --target "$TMP/t20" \
  > /dev/null 2>&1

assert_file_not_contains "$TMP/t20/AGENTS.md" "## Technical Stack"        "T20"
assert_file_contains     "$TMP/t20/AGENTS.md" "## Skills"                  "T20"
assert_file_contains     "$TMP/t20/AGENTS.md" "relational-database-design" "T20"

# T21 — compose: --full produces monolithic AGENTS.md with mode: full in lock file
run_test "T21 — compose: --full flag produces monolithic AGENTS.md"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t21" \
  --full \
  > /dev/null 2>&1

assert_file_exists "$TMP/t21/AGENTS.md" "T21"
assert_file_contains "$TMP/t21/AGENTS.md" "## Git Conventions" "T21"
assert_file_exists "$TMP/t21/.agentic/config.yaml" "T21"
assert_file_contains "$TMP/t21/.agentic/config.yaml" "mode: full" "T21"
assert_file_not_exists "$TMP/t21/.agentic/fragments" "T21"

# T22 — compose: lean default copies fragment files to target
run_test "T22 — compose: lean mode copies fragment files to .agentic/fragments/"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t22" \
  > /dev/null 2>&1

assert_file_exists "$TMP/t22/.agentic/fragments/git-conventions.md" "T22"
assert_file_exists "$TMP/t22/.agentic/fragments/go.md" "T22"
assert_file_exists "$TMP/t22/.agentic/fragments/cobra.md" "T22"
assert_file_contains "$TMP/t22/.agentic/config.yaml" "mode: lean" "T22"

# T23 — vendor-gen: copilot instructions are fully populated in lean mode
run_test "T23 — vendor-gen: copilot instructions contain fragment content in lean mode"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t23" \
  > /dev/null 2>&1

bash "$VENDOR_GEN" \
  --library "$LIBRARY" \
  --target "$TMP/t23" \
  --vendors copilot \
  > /dev/null 2>&1

assert_file_exists "$TMP/t23/.agentic/vendor-files/copilot/copilot-instructions.md" "T23"
assert_file_contains "$TMP/t23/.agentic/vendor-files/copilot/copilot-instructions.md" "Conventional Commits" "T23"
assert_file_contains "$TMP/t23/.agentic/vendor-files/copilot/copilot-instructions.md" "Git Conventions" "T23"

# T24 — compose: nested mode produces root AGENTS.md with tier table
run_test "T24 — compose: nested mode root AGENTS.md has Tiers section"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-nuxt-vite-ui \
  --target "$TMP/t24" > /dev/null 2>&1

assert_file_exists        "$TMP/t24/AGENTS.md"                                          "T24"
assert_file_contains      "$TMP/t24/AGENTS.md" "## Conventions & Patterns"              "T24"
assert_file_contains      "$TMP/t24/AGENTS.md" "## Tiers"                               "T24"
assert_file_contains      "$TMP/t24/AGENTS.md" "backend/AGENTS.md"                      "T24"
assert_file_contains      "$TMP/t24/AGENTS.md" "ui/AGENTS.md"                           "T24"
assert_file_contains      "$TMP/t24/AGENTS.md" ".agentic/fragments/tdd.md"              "T24"
assert_file_not_contains  "$TMP/t24/AGENTS.md" ".agentic/fragments/hexagonal.md"        "T24"
assert_file_not_contains  "$TMP/t24/AGENTS.md" ".agentic/fragments/vue.md"              "T24"
assert_file_contains      "$TMP/t24/.agentic/config.yaml" "structure: nested"           "T24"
assert_file_contains      "$TMP/t24/.agentic/config.yaml" "mode: lean"                  "T24"
assert_file_not_contains  "$TMP/t24/AGENTS.md"            "## Commands"                 "T24"

# T25 — compose: nested lean mode writes correct tier AGENTS.md files
run_test "T25 — compose: nested lean mode tier AGENTS.md content"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-nuxt-vite-ui \
  --target "$TMP/t25" > /dev/null 2>&1

assert_file_exists        "$TMP/t25/backend/AGENTS.md"                                  "T25"
assert_file_exists        "$TMP/t25/ui/AGENTS.md"                                       "T25"
assert_file_contains      "$TMP/t25/backend/AGENTS.md" ".agentic/fragments/typescript.md"  "T25"
assert_file_contains      "$TMP/t25/backend/AGENTS.md" ".agentic/fragments/hexagonal.md"   "T25"
assert_file_not_contains  "$TMP/t25/backend/AGENTS.md" ".agentic/fragments/vue.md"         "T25"
assert_file_not_contains  "$TMP/t25/backend/AGENTS.md" ".agentic/fragments/nuxt.md"        "T25"
assert_file_contains      "$TMP/t25/ui/AGENTS.md"      ".agentic/fragments/vue.md"         "T25"
assert_file_contains      "$TMP/t25/ui/AGENTS.md"      ".agentic/fragments/nuxt.md"        "T25"
assert_file_not_contains  "$TMP/t25/ui/AGENTS.md"      ".agentic/fragments/hexagonal.md"   "T25"
assert_file_not_contains  "$TMP/t25/backend/AGENTS.md" ".agentic/fragments/tdd.md"         "T25"
assert_file_not_contains  "$TMP/t25/ui/AGENTS.md"      ".agentic/fragments/tdd.md"         "T25"
assert_file_exists        "$TMP/t25/.agentic/fragments/hexagonal.md"                    "T25"
assert_file_exists        "$TMP/t25/.agentic/fragments/vue.md"                          "T25"
assert_file_contains      "$TMP/t25/backend/AGENTS.md" "## Commands"                    "T25"
assert_file_contains      "$TMP/t25/ui/AGENTS.md"      "## Commands"                    "T25"

# T26 — compose: nested --full inlines content into tier AGENTS.md files
run_test "T26 — compose: nested --full inlines fragment content in tier files"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-nuxt-vite-ui \
  --target "$TMP/t26" \
  --full > /dev/null 2>&1

assert_file_contains      "$TMP/t26/AGENTS.md"         "## Testing Philosophy"          "T26"
assert_file_not_contains  "$TMP/t26/AGENTS.md"         "## Hexagonal Architecture"      "T26"
assert_file_not_contains  "$TMP/t26/AGENTS.md"         "## Vue 3"                       "T26"
assert_file_contains      "$TMP/t26/backend/AGENTS.md" "## TypeScript"                  "T26"
assert_file_contains      "$TMP/t26/backend/AGENTS.md" "## Hexagonal Architecture"      "T26"
assert_file_not_contains  "$TMP/t26/backend/AGENTS.md" "## Vue 3"                       "T26"
assert_file_contains      "$TMP/t26/ui/AGENTS.md"      "## Vue 3"                       "T26"
assert_file_not_contains  "$TMP/t26/ui/AGENTS.md"      "## Hexagonal Architecture"      "T26"
assert_file_contains      "$TMP/t26/.agentic/config.yaml" "structure: nested"           "T26"

# T27 — compose: proprietary_libraries appear in correct locations
run_test "T27 — compose: proprietary_libraries sections in correct locations"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-nuxt-vite-ui \
  --target "$TMP/t27" > /dev/null 2>&1

assert_file_contains      "$TMP/t27/AGENTS.md"         "@acme/core"              "T27"
assert_file_contains      "$TMP/t27/AGENTS.md"         "Core domain primitives"  "T27"
assert_file_contains      "$TMP/t27/backend/AGENTS.md" "@acme/domain-kit"        "T27"
assert_file_contains      "$TMP/t27/backend/AGENTS.md" "docs.acme.internal"      "T27"
assert_file_contains      "$TMP/t27/ui/AGENTS.md"      "@acme/ui-tokens"         "T27"
assert_file_not_contains  "$TMP/t27/AGENTS.md"         "@acme/domain-kit"        "T27"
assert_file_not_contains  "$TMP/t27/AGENTS.md"         "@acme/ui-tokens"         "T27"

# T28 — vendor-switch: creates symlinks for the active vendor
run_test "T28 — vendor-switch: symlink-based switching from claude to gemini"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t28" \
  > /dev/null 2>&1

# Deploy skills so we can test skill symlinks
bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t28" \
  --skills code-review \
  > /dev/null 2>&1

# Activate claude vendor
bash "$VENDOR_SWITCH" \
  --library "$LIBRARY" \
  --target "$TMP/t28" \
  claude \
  > /dev/null 2>&1

# Claude should have CLAUDE.md symlink and .claude/skills symlink
assert_file_exists     "$TMP/t28/CLAUDE.md"                                   "T28 claude"
assert_file_exists     "$TMP/t28/.agentic/vendor-files/claude/CLAUDE.md"      "T28 claude"
assert_file_contains   "$TMP/t28/.agentic/config.yaml" "active_vendors:"      "T28 claude"
assert_file_contains   "$TMP/t28/.agentic/config.yaml" "  - claude"           "T28 claude"

# Now switch to gemini
bash "$VENDOR_SWITCH" \
  --library "$LIBRARY" \
  --target "$TMP/t28" \
  gemini \
  > /dev/null 2>&1

# Gemini should have symlink, claude symlinks should be gone
assert_file_exists "$TMP/t28/GEMINI.md"            "T28 gemini GEMINI.md root symlink"
assert_file_exists "$TMP/t28/.gemini/system.md"     "T28 gemini system.md"
assert_file_exists "$TMP/t28/.agentic/vendor-files/gemini/GEMINI.md" "T28 gemini vendor file"
assert_file_not_exists "$TMP/t28/CLAUDE.md"                                    "T28 gemini (no claude)"
assert_file_contains   "$TMP/t28/.agentic/config.yaml" "active_vendors:"       "T28 gemini"
assert_file_contains   "$TMP/t28/.agentic/config.yaml" "  - gemini"            "T28 gemini"
# Verify no stash directory exists (old system removed)
assert_file_not_exists "$TMP/t28/.agentic/vendor-stash"                        "T28 no stash"

# T29 — vendor-switch: list subcommand shows all vendors
run_test "T29 — vendor-switch: list subcommand shows all vendors"
T29_TMPFILE=$(mktemp "$TMP/t29-XXXXXX")
bash "$VENDOR_SWITCH" \
  --library "$LIBRARY" \
  --target "$TMP/t28" \
  list > "$T29_TMPFILE" 2>&1 || true

assert_file_contains "$T29_TMPFILE" "claude"   "T29"
assert_file_contains "$T29_TMPFILE" "copilot"  "T29"
assert_file_contains "$T29_TMPFILE" "codex"    "T29"
assert_file_contains "$T29_TMPFILE" "gemini"   "T29"
assert_file_contains "$T29_TMPFILE" "opencode" "T29"

# T30 — deploy-skills: creates vendor skill symlinks when --vendor is specified
run_test "T30 — deploy-skills: creates vendor skill symlinks"
mkdir -p "$TMP/t30"
bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t30" \
  --skills code-review \
  --vendor claude \
  > /dev/null 2>&1

# Should have canonical location and symlink
assert_file_exists "$TMP/t30/.agentic/skills/code-review/SKILL.md" "T30"
# Check .claude/skills is a symlink pointing to ../.agentic/skills
if [[ -L "$TMP/t30/.claude/skills" ]]; then
  pass "T30 — .claude/skills is a symlink"
else
  fail "T30 — .claude/skills should be a symlink"
fi

# T31 — deploy-skills: creates multiple vendor symlinks
run_test "T31 — deploy-skills: creates symlinks for multiple vendors"
mkdir -p "$TMP/t31"
bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t31" \
  --skills code-review \
  --vendor claude,codex,opencode \
  > /dev/null 2>&1

# Check all three vendor symlinks
if [[ -L "$TMP/t31/.claude/skills" ]]; then
  pass "T31 — .claude/skills is a symlink"
else
  fail "T31 — .claude/skills should be a symlink"
fi
if [[ -L "$TMP/t31/.agents/skills" ]]; then
  pass "T31 — .agents/skills is a symlink (codex)"
else
  fail "T31 — .agents/skills should be a symlink"
fi
if [[ -L "$TMP/t31/.opencode/skills" ]]; then
  pass "T31 — .opencode/skills is a symlink"
else
  fail "T31 — .opencode/skills should be a symlink"
fi

# T32 — vendor-switch: creates skill symlinks automatically
run_test "T32 — vendor-switch: creates skill symlinks for codex"
mkdir -p "$TMP/t32"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t32" \
  > /dev/null 2>&1

# Deploy skills first
bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t32" \
  --skills code-review \
  > /dev/null 2>&1

# Switch to codex
bash "$VENDOR_SWITCH" \
  --library "$LIBRARY" \
  --target "$TMP/t32" \
  codex \
  > /dev/null 2>&1

# Codex should have .agents/skills symlink
if [[ -L "$TMP/t32/.agents/skills" ]]; then
  pass "T32 — .agents/skills symlink created for codex"
else
  fail "T32 — .agents/skills should be a symlink for codex"
fi
assert_file_contains "$TMP/t32/.agentic/config.yaml" "active_vendors:" "T32"
assert_file_contains "$TMP/t32/.agentic/config.yaml" "  - codex" "T32"

# T33 — vendor-switch: migration removes old stash directory
run_test "T33 — vendor-switch: migrates from old stash system"
mkdir -p "$TMP/t33"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t33" \
  > /dev/null 2>&1

# Simulate old stash directory
mkdir -p "$TMP/t33/.agentic/vendor-stash/claude"
echo "old file" > "$TMP/t33/.agentic/vendor-stash/claude/CLAUDE.md"

# Run vendor-switch
bash "$VENDOR_SWITCH" \
  --library "$LIBRARY" \
  --target "$TMP/t33" \
  claude \
  > /dev/null 2>&1

# Old stash should be removed
assert_file_not_exists "$TMP/t33/.agentic/vendor-stash" "T33"
# New vendor-files should exist
assert_file_exists "$TMP/t33/.agentic/vendor-files/claude/CLAUDE.md" "T33"

# T34 — skills README contains vendor compatibility table
run_test "T34 — deploy-skills: README contains vendor compatibility info"
mkdir -p "$TMP/t34"
bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t34" \
  --skills code-review \
  > /dev/null 2>&1

assert_file_exists "$TMP/t34/.agentic/skills/README.md" "T34"
assert_file_contains "$TMP/t34/.agentic/skills/README.md" "Vendor Compatibility" "T34"
assert_file_contains "$TMP/t34/.agentic/skills/README.md" ".claude/skills" "T34"
assert_file_contains "$TMP/t34/.agentic/skills/README.md" ".agents/skills" "T34"
assert_file_contains "$TMP/t34/.agentic/skills/README.md" "code-review" "T34"

# ══════════════════════════════════════════════════════════════════════════════
# LOCAL PROFILE SUPPORT TESTS
# ══════════════════════════════════════════════════════════════════════════════

# T35 — compose: copies profile to .agentic/profile.yaml
run_test "T35 — compose: copies profile to .agentic/profile.yaml"
mkdir -p "$TMP/t35"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t35" \
  > /dev/null 2>&1

assert_file_exists "$TMP/t35/.agentic/profile.yaml" "T35"
assert_file_contains "$TMP/t35/.agentic/profile.yaml" "meta:" "T35"

# T36 — compose: --profile-file flag works with local profile
run_test "T36 — compose: --profile-file flag works with local profile"
mkdir -p "$TMP/t36"
# First compose to get a profile
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t36" \
  > /dev/null 2>&1

# Modify the local profile
yq -i '.meta.version = "99.0.0"' "$TMP/t36/.agentic/profile.yaml"

# Re-compose using local profile
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile-file "$TMP/t36/.agentic/profile.yaml" \
  --target "$TMP/t36" \
  > /dev/null 2>&1

assert_file_contains "$TMP/t36/AGENTS.md" "v99.0.0" "T36"

# T37 — sync.sh: regenerates from local profile
run_test "T37 — sync.sh: regenerates from local profile"
SYNC="$LIBRARY/tooling/lib/sync.sh"
mkdir -p "$TMP/t37"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t37" \
  > /dev/null 2>&1

# Modify the local profile version
yq -i '.meta.version = "88.0.0"' "$TMP/t37/.agentic/profile.yaml"

# Run sync
bash "$SYNC" --target "$TMP/t37" > /dev/null 2>&1

assert_file_contains "$TMP/t37/AGENTS.md" "v88.0.0" "T37"

# T38 — vendor-switch: sync subcommand works
run_test "T38 — vendor-switch: sync subcommand works"
mkdir -p "$TMP/t38"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t38" \
  > /dev/null 2>&1

# Activate a vendor first
bash "$VENDOR_SWITCH" \
  --library "$LIBRARY" \
  --target "$TMP/t38" \
  claude \
  > /dev/null 2>&1

# Modify the local profile version
yq -i '.meta.version = "77.0.0"' "$TMP/t38/.agentic/profile.yaml"

# Run sync via vendor-switch
bash "$VENDOR_SWITCH" \
  --library "$LIBRARY" \
  --target "$TMP/t38" \
  sync \
  > /dev/null 2>&1

assert_file_contains "$TMP/t38/AGENTS.md" "v77.0.0" "T38"
# Active vendors should be preserved
assert_file_contains "$TMP/t38/.agentic/config.yaml" "active_vendors:" "T38"
assert_file_contains "$TMP/t38/.agentic/config.yaml" "  - claude" "T38"

# T39 — deploy-skills: project: prefix deploys project-local skills
run_test "T39 — deploy-skills: project: prefix deploys project-local skills"
mkdir -p "$TMP/t39/.agentic/project-skills/my-custom-skill"
cat > "$TMP/t39/.agentic/project-skills/my-custom-skill/SKILL.md" <<'EOF'
---
name: my-custom-skill
description: A project-specific custom skill
version: 1.0.0
tags: [custom]
vendor_support: [claude, opencode]
---
# My Custom Skill

This is a custom project-local skill.
EOF

bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t39" \
  --skills "project:my-custom-skill" \
  > /dev/null 2>&1

assert_file_exists "$TMP/t39/.agentic/skills/my-custom-skill/SKILL.md" "T39"

# T40 — deploy-skills: missing project: skill warns but does not fail
run_test "T40 — deploy-skills: missing project: skill warns but does not fail"
mkdir -p "$TMP/t40"

# Deploy a missing project skill - should warn but exit 0
OUTPUT=$(bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t40" \
  --skills "project:nonexistent-skill" \
  2>&1) || true

if echo "$OUTPUT" | grep -q "Warning:.*nonexistent-skill"; then
  pass "T40 — warns about missing project skill"
else
  fail "T40 — should warn about missing project skill"
fi

# Should NOT have created the skill directory
assert_file_not_exists "$TMP/t40/.agentic/skills/nonexistent-skill" "T40"

# T41 — compose: gitignore managed block for vendor symlinks
run_test "T41 — compose: gitignore managed block for vendor symlinks"
mkdir -p "$TMP/t41"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t41" \
  > /dev/null 2>&1

# Gitignore should exist with managed block
assert_file_exists "$TMP/t41/.gitignore" "T41"
# Managed block delimiters
assert_file_contains "$TMP/t41/.gitignore" "# agentic:start" "T41"
assert_file_contains "$TMP/t41/.gitignore" "# agentic:end" "T41"
# Vendor skill symlinks
assert_file_contains "$TMP/t41/.gitignore" ".claude/skills" "T41"
assert_file_contains "$TMP/t41/.gitignore" ".opencode/skills" "T41"
assert_file_contains "$TMP/t41/.gitignore" ".agents/skills" "T41"
# Project-owned files must NOT be ignored
assert_file_not_contains "$TMP/t41/.gitignore" "AGENTS.md" "T41"
assert_file_not_contains "$TMP/t41/.gitignore" "config.yaml" "T41"
assert_file_not_contains "$TMP/t41/.gitignore" "profile.yaml" "T41"
assert_file_not_contains "$TMP/t41/.gitignore" "project-skills" "T41"
# Copy mode: runtime dirs must NOT be ignored (they are real committed files in copy mode)
assert_file_not_contains "$TMP/t41/.gitignore" ".agentic/skills/" "T41"
assert_file_not_contains "$TMP/t41/.gitignore" ".agentic/fragments/" "T41"
assert_file_not_contains "$TMP/t41/.gitignore" ".agentic/vendor-files/" "T41"

# T_GITIGNORE_LINK_MODE — link mode ignores runtime dirs
run_test "T_GITIGNORE_LINK_MODE — link mode ignores runtime dirs"
mkdir -p "$TMP/t_gl"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t_gl" \
  --link \
  > /dev/null 2>&1
assert_file_contains "$TMP/t_gl/.gitignore" ".agentic/skills/" "T_GITIGNORE_LINK_MODE"
assert_file_contains "$TMP/t_gl/.gitignore" ".agentic/fragments/" "T_GITIGNORE_LINK_MODE"
assert_file_contains "$TMP/t_gl/.gitignore" ".agentic/vendor-files/" "T_GITIGNORE_LINK_MODE"
assert_file_contains "$TMP/t_gl/.gitignore" "# agentic:start" "T_GITIGNORE_LINK_MODE"

# T_GITIGNORE_IDEMPOTENT — block not duplicated on re-run
run_test "T_GITIGNORE_IDEMPOTENT — block not duplicated on re-run"
mkdir -p "$TMP/t_gi"
bash "$COMPOSE" --library "$LIBRARY" --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t_gi" > /dev/null 2>&1
bash "$COMPOSE" --library "$LIBRARY" --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t_gi" > /dev/null 2>&1
count=$(grep -c "# agentic:start" "$TMP/t_gi/.gitignore" || true)
if [[ "$count" -eq 1 ]]; then
  pass "T_GITIGNORE_IDEMPOTENT — block appears exactly once"
else
  fail "T_GITIGNORE_IDEMPOTENT — block duplicated ($count occurrences)"
fi

# T_GITIGNORE_PRESERVE_USER — user entries survive compose
run_test "T_GITIGNORE_PRESERVE_USER — user entries survive compose"
mkdir -p "$TMP/t_gp"
printf '*.log\nnode_modules/\n' > "$TMP/t_gp/.gitignore"
bash "$COMPOSE" --library "$LIBRARY" --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t_gp" > /dev/null 2>&1
assert_file_contains "$TMP/t_gp/.gitignore" "*.log" "T_GITIGNORE_PRESERVE_USER"
assert_file_contains "$TMP/t_gp/.gitignore" "node_modules/" "T_GITIGNORE_PRESERVE_USER"
assert_file_contains "$TMP/t_gp/.gitignore" "# agentic:start" "T_GITIGNORE_PRESERVE_USER"

# T_GITIGNORE_UPDATE_BLOCK — outdated block is replaced not duplicated
run_test "T_GITIGNORE_UPDATE_BLOCK — outdated block is replaced not duplicated"
mkdir -p "$TMP/t_gu"
# Write a gitignore with an old-style managed block (fewer entries)
printf '*.log\n# agentic:start — managed block (do not edit manually, regenerated by agentic)\nCLAUDE.md\n# agentic:end\nnode_modules/\n' \
  > "$TMP/t_gu/.gitignore"
bash "$COMPOSE" --library "$LIBRARY" --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t_gu" > /dev/null 2>&1
# Block must appear exactly once
count=$(grep -c "# agentic:start" "$TMP/t_gu/.gitignore" || true)
if [[ "$count" -eq 1 ]]; then
  pass "T_GITIGNORE_UPDATE_BLOCK — block appears exactly once after update"
else
  fail "T_GITIGNORE_UPDATE_BLOCK — block duplicated ($count occurrences)"
fi
# User entries outside the block must survive
assert_file_contains "$TMP/t_gu/.gitignore" "*.log" "T_GITIGNORE_UPDATE_BLOCK"
assert_file_contains "$TMP/t_gu/.gitignore" "node_modules/" "T_GITIGNORE_UPDATE_BLOCK"
# New entry from current canonical block must be present
assert_file_contains "$TMP/t_gu/.gitignore" "GEMINI.md" "T_GITIGNORE_UPDATE_BLOCK"

# T_GITIGNORE_COPY_TO_LINK — runtime dirs added when upgrading to link mode
run_test "T_GITIGNORE_COPY_TO_LINK — runtime dirs added when upgrading to link mode"
mkdir -p "$TMP/t_c2l"
# First deploy: copy mode (no --link)
bash "$COMPOSE" --library "$LIBRARY" --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t_c2l" > /dev/null 2>&1
# Runtime dirs must NOT be in gitignore yet
assert_file_not_contains "$TMP/t_c2l/.gitignore" ".agentic/skills/" "T_GITIGNORE_COPY_TO_LINK"
# Second deploy: switch to link mode
bash "$COMPOSE" --library "$LIBRARY" --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t_c2l" --link > /dev/null 2>&1
# Runtime dirs MUST now be ignored
assert_file_contains "$TMP/t_c2l/.gitignore" ".agentic/skills/" "T_GITIGNORE_COPY_TO_LINK"
assert_file_contains "$TMP/t_c2l/.gitignore" ".agentic/fragments/" "T_GITIGNORE_COPY_TO_LINK"
assert_file_contains "$TMP/t_c2l/.gitignore" ".agentic/vendor-files/" "T_GITIGNORE_COPY_TO_LINK"
# Exactly one managed block
count=$(grep -c "# agentic:start" "$TMP/t_c2l/.gitignore" || true)
if [[ "$count" -eq 1 ]]; then
  pass "T_GITIGNORE_COPY_TO_LINK — single managed block after upgrade"
else
  fail "T_GITIGNORE_COPY_TO_LINK — block duplicated ($count occurrences)"
fi

# T_GITIGNORE_LINK_TO_COPY — runtime dirs removed when downgrading to copy mode
run_test "T_GITIGNORE_LINK_TO_COPY — runtime dirs removed when downgrading to copy mode"
mkdir -p "$TMP/t_l2c"
# First deploy: link mode
bash "$COMPOSE" --library "$LIBRARY" --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t_l2c" --link > /dev/null 2>&1
# Runtime dirs must be in gitignore
assert_file_contains "$TMP/t_l2c/.gitignore" ".agentic/skills/" "T_GITIGNORE_LINK_TO_COPY"
# Second deploy: switch to copy mode (no --link)
bash "$COMPOSE" --library "$LIBRARY" --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t_l2c" > /dev/null 2>&1
# Runtime dirs must NO LONGER be ignored
assert_file_not_contains "$TMP/t_l2c/.gitignore" ".agentic/skills/" "T_GITIGNORE_LINK_TO_COPY"
assert_file_not_contains "$TMP/t_l2c/.gitignore" ".agentic/fragments/" "T_GITIGNORE_LINK_TO_COPY"
assert_file_not_contains "$TMP/t_l2c/.gitignore" ".agentic/vendor-files/" "T_GITIGNORE_LINK_TO_COPY"
# Exactly one managed block
count=$(grep -c "# agentic:start" "$TMP/t_l2c/.gitignore" || true)
if [[ "$count" -eq 1 ]]; then
  pass "T_GITIGNORE_LINK_TO_COPY — single managed block after downgrade"
else
  fail "T_GITIGNORE_LINK_TO_COPY — block duplicated ($count occurrences)"
fi

# T42 — deploy: activates the first vendor automatically
run_test "T42 — deploy: activates the first vendor automatically"
mkdir -p "$TMP/t42"
# Simulate what 'just deploy' does: compose + vendor-gen + deploy-skills + vendor-switch
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t42" \
  > /dev/null 2>&1

bash "$VENDOR_GEN" \
  --library "$LIBRARY" \
  --target "$TMP/t42" \
  --vendors opencode \
  > /dev/null 2>&1

bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t42" \
  --skills code-review \
  --vendor opencode \
  > /dev/null 2>&1

# Activate the vendor (simulating what justfile deploy does)
bash "$VENDOR_SWITCH" \
  --library "$LIBRARY" \
  --target "$TMP/t42" \
  opencode \
  > /dev/null 2>&1

# active_vendors should be set
assert_file_contains "$TMP/t42/.agentic/config.yaml" "active_vendors:" "T42"
assert_file_contains "$TMP/t42/.agentic/config.yaml" "  - opencode" "T42"
# Symlink should exist
if [[ -L "$TMP/t42/.opencode/skills" ]]; then
  pass "T42 — .opencode/skills symlink created"
else
  fail "T42 — .opencode/skills symlink should be created"
fi
# opencode.json should NOT exist (users manage their own config)
assert_file_not_exists "$TMP/t42/.agentic/vendor-files/opencode/opencode.json" "T42"

# T43 — vendor-switch: multi-vendor activation
run_test "T43 — vendor-switch: multi-vendor activation"
mkdir -p "$TMP/t43"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t43" \
  > /dev/null 2>&1

# Generate vendor files for both
bash "$VENDOR_GEN" \
  --library "$LIBRARY" \
  --target "$TMP/t43" \
  --vendors claude,copilot \
  > /dev/null 2>&1

# Activate multiple vendors using comma-separated format
bash "$VENDOR_SWITCH" \
  --library "$LIBRARY" \
  --target "$TMP/t43" \
  claude,copilot \
  > /dev/null 2>&1

# active_vendors should contain both
assert_file_contains "$TMP/t43/.agentic/config.yaml" "active_vendors:" "T43"
assert_file_contains "$TMP/t43/.agentic/config.yaml" "  - claude" "T43"
assert_file_contains "$TMP/t43/.agentic/config.yaml" "  - copilot" "T43"

# Both vendor symlinks should exist
assert_file_exists "$TMP/t43/CLAUDE.md" "T43 claude symlink"
assert_file_exists "$TMP/t43/.github/copilot-instructions.md" "T43 copilot symlink"

# Now switch to single vendor - should replace the set
bash "$VENDOR_SWITCH" \
  --library "$LIBRARY" \
  --target "$TMP/t43" \
  gemini \
  > /dev/null 2>&1

# Only gemini should be active now
assert_file_contains "$TMP/t43/.agentic/config.yaml" "  - gemini" "T43 replace"
assert_file_not_exists "$TMP/t43/CLAUDE.md" "T43 claude removed"
assert_file_not_exists "$TMP/t43/.github/copilot-instructions.md" "T43 copilot removed"
assert_file_exists "$TMP/t43/GEMINI.md"         "T43 gemini active GEMINI.md"
assert_file_exists "$TMP/t43/.gemini/system.md"  "T43 gemini active system.md"

# ══════════════════════════════════════════════════════════════════════════════
# GLOBAL CLI TESTS
# ══════════════════════════════════════════════════════════════════════════════

# T44 — CLI: --help shows usage
run_test "T44 — CLI: --help shows usage"
CLI="$LIBRARY/bin/agentic"
T44_OUTPUT=$("$CLI" --help 2>&1) || true

assert_stdout_contains "$T44_OUTPUT" "agentic" "T44"
assert_stdout_contains "$T44_OUTPUT" "Usage:" "T44"
assert_stdout_contains "$T44_OUTPUT" "deploy" "T44"
assert_stdout_contains "$T44_OUTPUT" "compose" "T44"
assert_stdout_contains "$T44_OUTPUT" "init" "T44"
assert_stdout_contains "$T44_OUTPUT" "switch" "T44"
assert_stdout_contains "$T44_OUTPUT" "sync" "T44"

# T45 — CLI: version command works
run_test "T45 — CLI: version command works"
T45_OUTPUT=$("$CLI" version 2>&1) || true

assert_stdout_contains "$T45_OUTPUT" "agentic version" "T45"

# T46 — CLI: list profiles works
run_test "T46 — CLI: list profiles works"
T46_OUTPUT=$(AGENTIC_REPO_ROOT="$LIBRARY" "$CLI" list profiles 2>&1) || true

assert_stdout_contains "$T46_OUTPUT" "Available profiles:" "T46"
assert_stdout_contains "$T46_OUTPUT" "golang-hexagonal-cobra-cli" "T46"

# T47 — CLI: list vendors works
run_test "T47 — CLI: list vendors works"
T47_OUTPUT=$(AGENTIC_REPO_ROOT="$LIBRARY" "$CLI" list vendors 2>&1) || true

assert_stdout_contains "$T47_OUTPUT" "Supported vendors:" "T47"
assert_stdout_contains "$T47_OUTPUT" "claude" "T47"
assert_stdout_contains "$T47_OUTPUT" "copilot" "T47"
assert_stdout_contains "$T47_OUTPUT" "gemini" "T47"

# ══════════════════════════════════════════════════════════════════════════════
# LIBRARY DISCOVERY TESTS
# ══════════════════════════════════════════════════════════════════════════════

# T48 — CLI: AGENTIC_REPO_ROOT env var is used for library discovery
run_test "T48 — CLI: AGENTIC_REPO_ROOT env var discovery"
T48_OUTPUT=$(AGENTIC_REPO_ROOT="$LIBRARY" "$CLI" list vendors 2>&1) || true

assert_stdout_contains "$T48_OUTPUT" "Supported vendors:" "T48"

# T49 — CLI: AGENTIC_ROOT env var is used as fallback
run_test "T49 — CLI: AGENTIC_ROOT env var fallback"
T49_OUTPUT=$(AGENTIC_ROOT="$LIBRARY" "$CLI" list vendors 2>&1) || true

assert_stdout_contains "$T49_OUTPUT" "Supported vendors:" "T49"

# T50 — CLI: agentic_root from config.yaml is used when no env var
run_test "T50 — CLI: agentic_root from config.yaml discovery"
mkdir -p "$TMP/t50/.agentic"
cat > "$TMP/t50/.agentic/config.yaml" <<CONFIG
agentic_root: "$LIBRARY"
active_vendors: []
CONFIG

# Run from within the target directory
T50_OUTPUT=$(cd "$TMP/t50" && "$CLI" list vendors 2>&1) || true

assert_stdout_contains "$T50_OUTPUT" "Supported vendors:" "T50"

# T51 — CLI: fails with helpful error when no library found
run_test "T51 — CLI: fails when no library found"
mkdir -p "$TMP/t51"

# Test discover_library() directly with all discovery methods disabled
# (unset LIBRARY_ROOT, no env vars, no config file)
T51_EXIT=0
T51_OUTPUT=$(cd "$TMP/t51" && unset LIBRARY_ROOT && bash -c '
  unset AGENTIC_REPO_ROOT AGENTIC_ROOT LIBRARY_ROOT
  source "'"$LIBRARY"'/tooling/lib/cli.sh"
  discover_library
' 2>&1) || T51_EXIT=$?

assert_exit_code 1 "$T51_EXIT" "T51"
assert_stdout_contains "$T51_OUTPUT" "AGENTIC_REPO_ROOT" "T51"

# ══════════════════════════════════════════════════════════════════════════════
# UNINSTALL & SMART INSTALLER TESTS
# ══════════════════════════════════════════════════════════════════════════════

# T_UNINSTALL_HELP — CLI: uninstall --help shows usage
run_test "T_UNINSTALL_HELP — CLI: uninstall --help shows usage"
T_UNINSTALL_HELP_OUT=$(AGENTIC_REPO_ROOT="$LIBRARY" "$CLI" uninstall --help 2>&1) || true
assert_stdout_contains "$T_UNINSTALL_HELP_OUT" "uninstall"  "T_UNINSTALL_HELP"
assert_stdout_contains "$T_UNINSTALL_HELP_OUT" "--global"   "T_UNINSTALL_HELP"

# T_UNINSTALL_HELP_GLOBAL — CLI: help uninstall routes to uninstall help
run_test "T_UNINSTALL_HELP_GLOBAL — CLI: help uninstall shows usage"
T_UNINSTALL_HELP_GLOBAL_OUT=$(AGENTIC_REPO_ROOT="$LIBRARY" "$CLI" help uninstall 2>&1) || true
assert_stdout_contains "$T_UNINSTALL_HELP_GLOBAL_OUT" "uninstall" "T_UNINSTALL_HELP_GLOBAL"

# T_UNINSTALL_IN_HELP — CLI: main --help table includes uninstall
run_test "T_UNINSTALL_IN_HELP — CLI: main --help lists uninstall command"
T_UNINSTALL_IN_HELP_OUT=$("$CLI" --help 2>&1) || true
assert_stdout_contains "$T_UNINSTALL_IN_HELP_OUT" "uninstall" "T_UNINSTALL_IN_HELP"

# T_UNINSTALL_NOOP — CLI: uninstall when not installed exits cleanly
run_test "T_UNINSTALL_NOOP — CLI: uninstall when not installed exits 0"
T_UNINSTALL_NOOP_HOME="$TMP/t_uninstall_noop_home"
mkdir -p "$T_UNINSTALL_NOOP_HOME"
T_UNINSTALL_NOOP_OUT=$(HOME="$T_UNINSTALL_NOOP_HOME" \
  AGENTIC_REPO_ROOT="$LIBRARY" \
  "$CLI" uninstall 2>&1) || true
assert_stdout_contains "$T_UNINSTALL_NOOP_OUT" "not installed" "T_UNINSTALL_NOOP"

# T_UNINSTALL_REMOVES — CLI: install to temp dir then uninstall removes binary
run_test "T_UNINSTALL_REMOVES — CLI: uninstall removes installed binary"
T_UNINSTALL_HOME="$TMP/t_uninstall_home"
mkdir -p "$T_UNINSTALL_HOME/.local/bin"
HOME="$T_UNINSTALL_HOME" \
  bash "$LIBRARY/tooling/lib/install.sh" install local > /dev/null 2>&1
assert_file_exists "$T_UNINSTALL_HOME/.local/bin/agentic" "T_UNINSTALL_REMOVES install"
HOME="$T_UNINSTALL_HOME" \
  AGENTIC_REPO_ROOT="$LIBRARY" \
  "$CLI" uninstall > /dev/null 2>&1
if [[ ! -f "$T_UNINSTALL_HOME/.local/bin/agentic" ]]; then
  pass "T_UNINSTALL_REMOVES — binary removed after uninstall"
else
  fail "T_UNINSTALL_REMOVES — binary still present after uninstall"
fi

# T_INSTALL_SH_HELP_WORKS — install.sh: --help exits 0 cleanly
run_test "T_INSTALL_SH_HELP_WORKS — install.sh --help exits 0"
T_INSTALL_HELP_EXIT=0
bash "$LIBRARY/install.sh" --help > /dev/null 2>&1 || T_INSTALL_HELP_EXIT=$?
if [[ "$T_INSTALL_HELP_EXIT" -eq 0 ]]; then
  pass "T_INSTALL_SH_HELP_WORKS — exit 0"
else
  fail "T_INSTALL_SH_HELP_WORKS — unexpected exit $T_INSTALL_HELP_EXIT"
fi

# T_INSTALL_SH_DETECTS_ARCH — install.sh: --help output mentions installer
run_test "T_INSTALL_SH_DETECTS_ARCH — install.sh --help shows installer header"
T_INSTALL_SH_OUT=$(bash "$LIBRARY/install.sh" --help 2>&1) || true
assert_stdout_contains "$T_INSTALL_SH_OUT" "agentic installer" "T_INSTALL_SH_DETECTS_ARCH"

# T52 — CLI: fails when library path doesn't exist
run_test "T52 — CLI: fails when library path doesn't exist"
T52_EXIT=0
T52_OUTPUT=$(AGENTIC_REPO_ROOT="/nonexistent/path" "$CLI" list profiles 2>&1) || T52_EXIT=$?

assert_exit_code 1 "$T52_EXIT" "T52"
assert_stdout_contains "$T52_OUTPUT" "does not exist" "T52"

# ══════════════════════════════════════════════════════════════════════════════
# TARGET AUTO-DETECTION TESTS
# ══════════════════════════════════════════════════════════════════════════════

# T53 — CLI: auto-detects target from current directory
run_test "T53 — CLI: auto-detects target from current directory"
mkdir -p "$TMP/t53/.agentic"
cat > "$TMP/t53/.agentic/config.yaml" <<CONFIG
agentic_root: "$LIBRARY"
profile: "golang-hexagonal-cobra-cli"
active_vendors: []
CONFIG
cat > "$TMP/t53/.agentic/profile.yaml" <<PROFILE
meta:
  name: Test Profile
  version: "1.0.0"
  description: Test
fragments:
  base:
    - git-conventions
PROFILE

# Run sync from within the directory (should auto-detect)
T53_OUTPUT=$(cd "$TMP/t53" && "$CLI" sync 2>&1) || true

assert_stdout_contains "$T53_OUTPUT" "Composed" "T53"

# T54 — CLI: auto-detects target from subdirectory
run_test "T54 — CLI: auto-detects target from subdirectory"
mkdir -p "$TMP/t54/.agentic"
mkdir -p "$TMP/t54/src/deep/nested"
cat > "$TMP/t54/.agentic/config.yaml" <<CONFIG
agentic_root: "$LIBRARY"
profile: "golang-hexagonal-cobra-cli"
active_vendors: []
CONFIG
cat > "$TMP/t54/.agentic/profile.yaml" <<PROFILE
meta:
  name: Test Profile
  version: "1.0.0"
  description: Test
fragments:
  base:
    - git-conventions
PROFILE

# Run sync from a subdirectory (should find config in parent)
T54_OUTPUT=$(cd "$TMP/t54/src/deep/nested" && "$CLI" sync 2>&1) || true

assert_stdout_contains "$T54_OUTPUT" "Composed" "T54"

# T55 — CLI: auto-detects target from config in parent
run_test "T55 — CLI: auto-detects target from config in parent"
mkdir -p "$TMP/t55/.agentic"
mkdir -p "$TMP/t55/src"
cat > "$TMP/t55/.agentic/config.yaml" <<CONFIG
agentic_root: "$LIBRARY"
profile: "golang-hexagonal-cobra-cli"
active_vendors: []
CONFIG
cat > "$TMP/t55/.agentic/profile.yaml" <<PROFILE
meta:
  name: Test Profile
  version: "1.0.0"
  description: Test
fragments:
  base:
    - git-conventions
PROFILE

# Run sync from a subdirectory (should find config in parent dir)
T55_EXIT=0
T55_OUTPUT=$(cd "$TMP/t55/src" && AGENTIC_REPO_ROOT="$LIBRARY" "$CLI" sync 2>&1) || T55_EXIT=$?

assert_exit_code 0 "$T55_EXIT" "T55"
assert_stdout_contains "$T55_OUTPUT" "Composed" "T55"

# ══════════════════════════════════════════════════════════════════════════════
# INSTALL SCRIPT TESTS
# ══════════════════════════════════════════════════════════════════════════════

# T56 — install.sh: shows usage without arguments
run_test "T56 — install.sh: shows usage without arguments"
INSTALL="$LIBRARY/tooling/lib/install.sh"
T56_OUTPUT=$("$INSTALL" 2>&1) || true

assert_stdout_contains "$T56_OUTPUT" "Usage:" "T56"
assert_stdout_contains "$T56_OUTPUT" "install" "T56"
assert_stdout_contains "$T56_OUTPUT" "uninstall" "T56"

# T57 — remote install.sh: shows help
run_test "T57 — remote install.sh: shows help"
REMOTE_INSTALL="$LIBRARY/install.sh"
T57_OUTPUT=$("$REMOTE_INSTALL" --help 2>&1) || true

assert_stdout_contains "$T57_OUTPUT" "One library. One deploy." "T57"
assert_stdout_contains "$T57_OUTPUT" "--dir" "T57"
assert_stdout_contains "$T57_OUTPUT" "--global" "T57"
assert_stdout_contains "$T57_OUTPUT" "--branch" "T57"

# ══════════════════════════════════════════════════════════════════════════════
# MCP SERVER SEEDING TESTS (profile mcp: key)
# ══════════════════════════════════════════════════════════════════════════════

# T67 — compose: MCP seed creates .mcp.json with correct keys
run_test "T67 — compose: MCP seed creates .mcp.json"
# Create a profile with mcp.servers
mkdir -p "$TMP/t67"
cat > "$TMP/t67-profile.yaml" <<'EOF'
meta:
  name: Test MCP Profile
  description: Test profile with MCP servers
  version: "1.0.0"
fragments:
  base:
    - git-conventions
output:
  build_command: ""
  test_command: ""
  lint_command: ""
vendors:
  enabled: []
mcp:
  strategy: merge
  servers:
    github:
      type: stdio
      command: npx
      args: ["-y", "@modelcontextprotocol/server-github"]
    postgres:
      type: stdio
      command: npx
      args: ["-y", "@modelcontextprotocol/server-postgres"]
      env:
        DATABASE_URL: "postgresql://localhost:5432"
EOF

bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile-file "$TMP/t67-profile.yaml" \
  --target "$TMP/t67" \
  > /dev/null 2>&1

assert_file_exists "$TMP/t67/.mcp.json" "T67"
assert_json_valid "$TMP/t67/.mcp.json" "T67"
assert_file_contains "$TMP/t67/.mcp.json" "github" "T67"
assert_file_contains "$TMP/t67/.mcp.json" "postgres" "T67"
assert_file_contains "$TMP/t67/.mcp.json" '"command": "npx"' "T67"

# T68 — compose: MCP seed writes to opencode.json with translations
run_test "T68 — compose: MCP seed translates for opencode.json"
mkdir -p "$TMP/t68"
# Create opencode.json first (simulating existing vendor)
echo '{"mcp":{}}' > "$TMP/t68/opencode.json"

cat > "$TMP/t68-profile.yaml" <<'EOF'
meta:
  name: Test MCP Opencode
  description: Test profile with MCP servers for opencode
  version: "1.0.0"
fragments:
  base:
    - git-conventions
output:
  build_command: ""
  test_command: ""
  lint_command: ""
vendors:
  enabled: []
mcp:
  servers:
    test-server:
      type: stdio
      command: npx
      args: ["-y", "some-server"]
      env:
        MY_TOKEN: "${MY_TOKEN}"
EOF

bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile-file "$TMP/t68-profile.yaml" \
  --target "$TMP/t68" \
  > /dev/null 2>&1

assert_file_exists "$TMP/t68/opencode.json" "T68"
assert_file_contains "$TMP/t68/opencode.json" '"local"' "T68"
assert_file_contains "$TMP/t68/opencode.json" '"environment"' "T68"

# T69 — compose: MCP seed writes to .gemini/settings.json without type field
run_test "T69 — compose: MCP seed translates for .gemini/settings.json"
mkdir -p "$TMP/t69/.gemini"
echo '{"mcpServers":{}}' > "$TMP/t69/.gemini/settings.json"

cat > "$TMP/t69-profile.yaml" <<'EOF'
meta:
  name: Test MCP Gemini
  description: Test profile with MCP servers for gemini
  version: "1.0.0"
fragments:
  base:
    - git-conventions
output:
  build_command: ""
  test_command: ""
  lint_command: ""
vendors:
  enabled: []
mcp:
  servers:
    http-server:
      type: http
      url: "http://localhost:3000"
EOF

bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile-file "$TMP/t69-profile.yaml" \
  --target "$TMP/t69" \
  > /dev/null 2>&1

assert_file_exists "$TMP/t69/.gemini/settings.json" "T69"
assert_file_contains "$TMP/t69/.gemini/settings.json" "http-server" "T69"
assert_file_contains "$TMP/t69/.gemini/settings.json" "httpUrl" "T69"
# Should NOT contain 'type' field
assert_file_not_contains "$TMP/t69/.gemini/settings.json" '"type"' "T69"

# T70 — compose: MCP merge strategy preserves existing servers
run_test "T70 — compose: MCP merge preserves existing servers"
mkdir -p "$TMP/t70"
# Pre-existing .mcp.json with a server
echo '{"mcpServers":{"existing-server":{"type":"stdio","command":"echo","args":["hello"]}}}' > "$TMP/t70/.mcp.json"

cat > "$TMP/t70-profile.yaml" <<'EOF'
meta:
  name: Test MCP Merge
  description: Test profile with MCP servers merge
  version: "1.0.0"
fragments:
  base:
    - git-conventions
output:
  build_command: ""
  test_command: ""
  lint_command: ""
vendors:
  enabled: []
mcp:
  strategy: merge
  servers:
    new-server:
      type: stdio
      command: echo
      args: ["new"]
EOF

bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile-file "$TMP/t70-profile.yaml" \
  --target "$TMP/t70" \
  > /dev/null 2>&1

assert_file_contains "$TMP/t70/.mcp.json" "existing-server" "T70"
assert_file_contains "$TMP/t70/.mcp.json" "new-server" "T70"

# T71 — compose: MCP replace strategy removes old servers
run_test "T71 — compose: MCP replace removes old servers"
mkdir -p "$TMP/t71"
echo '{"mcpServers":{"old-server":{"type":"stdio","command":"old","args":["old"]}}}' > "$TMP/t71/.mcp.json"

cat > "$TMP/t71-profile.yaml" <<'EOF'
meta:
  name: Test MCP Replace
  description: Test profile with MCP servers replace
  version: "1.0.0"
fragments:
  base:
    - git-conventions
output:
  build_command: ""
  test_command: ""
  lint_command: ""
vendors:
  enabled: []
mcp:
  strategy: replace
  servers:
    brand-new:
      type: http
      url: "http://localhost:8080"
EOF

bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile-file "$TMP/t71-profile.yaml" \
  --target "$TMP/t71" \
  > /dev/null 2>&1

assert_file_contains "$TMP/t71/.mcp.json" "brand-new" "T71"
assert_file_not_contains "$TMP/t71/.mcp.json" "old-server" "T71"

# T72 — compose: profile without mcp key produces no MCP files
run_test "T72 — compose: profile without mcp key is no-op"
mkdir -p "$TMP/t72"

cat > "$TMP/t72-profile.yaml" <<'EOF'
meta:
  name: Test No MCP
  description: Test profile without MCP servers
  version: "1.0.0"
fragments:
  base:
    - git-conventions
output:
  build_command: ""
  test_command: ""
  lint_command: ""
vendors:
  enabled: []
EOF

bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile-file "$TMP/t72-profile.yaml" \
  --target "$TMP/t72" \
  > /dev/null 2>&1

# Should not touch vendor MCP files (none should exist)
assert_file_not_exists "$TMP/t72/.mcp.json" "T72"
assert_file_not_exists "$TMP/t72/opencode.json" "T72"
assert_file_not_exists "$TMP/t72/.gemini/settings.json" "T72"

# T73 — lint: schema validation passes with mcp key
run_test "T73 — lint: schema validation passes with mcp key"
T73_EXIT=0
bash "$LINT" \
  --library "$LIBRARY" \
  > /dev/null 2>&1 || T73_EXIT=$?

assert_exit_code 0 "$T73_EXIT" "T73"

# ══════════════════════════════════════════════════════════════════════════════
# INDEX STABILITY TESTS
# ══════════════════════════════════════════════════════════════════════════════

# T58 — index.sh: does not update unchanged content
run_test "T58 — index.sh: does not update unchanged content"
T58_OUTPUT=$(bash "$INDEX" --library "$LIBRARY" 2>&1)

assert_stdout_contains "$T58_OUTPUT" "Unchanged: index/skills.json" "T58"
assert_stdout_contains "$T58_OUTPUT" "Unchanged: index/fragments.json" "T58"

# T59 — CLI: LIBRARY_ROOT fallback discovery
run_test "T59 — CLI: LIBRARY_ROOT fallback discovery"
# Simulate installed CLI by setting LIBRARY_ROOT and NOT setting env vars or config
T59_OUTPUT=$(cd "$TMP" && LIBRARY_ROOT="$LIBRARY" bash -c 'source "$1/tooling/lib/cli.sh"; discover_library' -- "$LIBRARY" 2>&1)

assert_stdout_contains "$T59_OUTPUT" "$LIBRARY" "T59"

# ══════════════════════════════════════════════════════════════════════════════
# SYMLINK DEPLOY MODE TESTS (--link flag)
# ══════════════════════════════════════════════════════════════════════════════

SYNC_LINKS="$LIBRARY/tooling/lib/sync-links.sh"

# T60 — compose --link: .agentic/fragments is a symlink, not a copied directory
run_test "T60 — compose --link: fragments is a symlink"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile go-hexagonal-microservice \
  --target "$TMP/t60" \
  --link \
  > /dev/null 2>&1 || true

if [[ -L "$TMP/t60/.agentic/fragments" ]]; then
  pass "T60 — .agentic/fragments is a symlink"
else
  fail "T60 — .agentic/fragments should be a symlink, not a real directory"
fi
assert_file_contains "$TMP/t60/.agentic/config.yaml" "deploy_mode: link" "T60"

# T61 — compose --link: AGENTS.md is still generated correctly
run_test "T61 — compose --link: AGENTS.md generated correctly"
assert_file_exists "$TMP/t60/AGENTS.md" "T61"
assert_file_contains "$TMP/t60/AGENTS.md" "<!-- AUTO-GENERATED by agentic library -->" "T61"
assert_file_contains "$TMP/t60/AGENTS.md" "## Conventions & Patterns" "T61"

# T62 — deploy-skills --link: .agentic/skills is a symlink
run_test "T62 — deploy-skills --link: skills is a symlink"
bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t60" \
  --skills all \
  --link \
  > /dev/null 2>&1 || true

if [[ -L "$TMP/t60/.agentic/skills" ]]; then
  pass "T62 — .agentic/skills is a symlink"
else
  fail "T62 — .agentic/skills should be a symlink"
fi
# Skill files must still be accessible through the symlink
# Skills are in subdirectories under $LIBRARY/skills/ (e.g. development/code-review/),
# accessible as .agentic/skills/development/code-review/SKILL.md
assert_file_exists "$TMP/t60/.agentic/skills/development/code-review/SKILL.md" "T62 skill accessible"

# T63 — vendor-gen --link: .agentic/vendor-files is a symlink
run_test "T63 — vendor-gen --link: vendor-files is a symlink"
bash "$VENDOR_GEN" \
  --library "$LIBRARY" \
  --target "$TMP/t60" \
  --vendors claude \
  --link \
  > /dev/null 2>&1 || true

if [[ -L "$TMP/t60/.agentic/vendor-files" ]]; then
  pass "T63 — .agentic/vendor-files is a symlink"
else
  fail "T63 — .agentic/vendor-files should be a symlink"
fi
assert_file_exists "$TMP/t60/.agentic/vendor-files/claude/CLAUDE.md" "T63 vendor file accessible"

# T64 — config.yaml: deploy_mode and agentic_root are set in link mode
run_test "T64 — config.yaml contains deploy_mode: link and agentic_root"
assert_file_contains "$TMP/t60/.agentic/config.yaml" "deploy_mode: link" "T64"
assert_file_contains "$TMP/t60/.agentic/config.yaml" "agentic_root:" "T64"

# T65 — sync-links: re-creates a deleted symlink
run_test "T65 — sync-links: re-creates deleted symlink"
# Delete the fragments symlink
rm "$TMP/t60/.agentic/fragments" 2>/dev/null || true
# Run sync-links
bash "$SYNC_LINKS" \
  --target "$TMP/t60" \
  > /dev/null 2>&1 || true
if [[ -L "$TMP/t60/.agentic/fragments" ]]; then
  pass "T65 — .agentic/fragments symlink re-created by sync-links"
else
  fail "T65 — sync-links failed to re-create .agentic/fragments symlink"
fi

# T66 — regression: compose without --link still copies files (not symlinks)
run_test "T66 — regression: compose without --link uses real directories"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile go-hexagonal-microservice \
  --target "$TMP/t66" \
  > /dev/null 2>&1

if [[ ! -L "$TMP/t66/.agentic/fragments" ]] && [[ -d "$TMP/t66/.agentic/fragments" ]]; then
  pass "T66 — .agentic/fragments is a real directory (not a symlink)"
else
  fail "T66 — .agentic/fragments should be a real directory in copy mode"
fi
assert_file_not_contains "$TMP/t66/.agentic/config.yaml" "deploy_mode: link" "T66"

# ══════════════════════════════════════════════════════════════════════════════
# CUSTOM RULES / AGENTS.LOCAL.MD TESTS
# ══════════════════════════════════════════════════════════════════════════════

# T74 — compose: AGENTS.local.md appears in output (append, default)
run_test "T74 — compose: AGENTS.local.md appears in output (append)"
mkdir -p "$TMP/t74"
cat > "$TMP/t74/AGENTS.local.md" <<'EOF'
## Custom Rules

These are my project-specific rules.
EOF

bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t74" \
  > /dev/null 2>&1

assert_file_exists "$TMP/t74/AGENTS.md" "T74"
assert_file_contains "$TMP/t74/AGENTS.md" "<!-- local override: AGENTS.local.md -->" "T74"
assert_file_contains "$TMP/t74/AGENTS.md" "## Custom Rules" "T74"
assert_file_contains "$TMP/t74/AGENTS.md" "These are my project-specific rules." "T74"

# T75 — compose: custom_rules.placement: prepend places local content first
run_test "T75 — compose: custom_rules.placement: prepend"
mkdir -p "$TMP/t75"
cat > "$TMP/t75-profile.yaml" <<'EOF'
meta:
  name: Test Prepend
  description: Test profile with prepend placement
  version: "1.0.0"
fragments:
  base:
    - git-conventions
output:
  build_command: ""
  test_command: ""
  lint_command: ""
  custom_rules:
    placement: prepend
vendors:
  enabled: []
EOF

cat > "$TMP/t75/AGENTS.local.md" <<'EOF'
## Prepended Section

This should appear near the top.
EOF

bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile-file "$TMP/t75-profile.yaml" \
  --target "$TMP/t75" \
  > /dev/null 2>&1

assert_file_exists "$TMP/t75/AGENTS.md" "T75"
assert_file_contains "$TMP/t75/AGENTS.md" "<!-- local override: AGENTS.local.md -->" "T75"
assert_file_contains "$TMP/t75/AGENTS.md" "## Prepended Section" "T75"

# T76 — compose: custom_rules.placement: after_section injects after named section
run_test "T76 — compose: custom_rules.placement: after_section"
mkdir -p "$TMP/t76"
cat > "$TMP/t76-profile.yaml" <<'EOF'
meta:
  name: Test After Section
  description: Test profile with after_section placement
  version: "1.0.0"
fragments:
  base:
    - git-conventions
output:
  build_command: ""
  test_command: ""
  lint_command: ""
  custom_rules:
    placement: after_section
    after_section: "Commands"
vendors:
  enabled: []
EOF

cat > "$TMP/t76/AGENTS.local.md" <<'EOF'
## Post-Commands Section

This should appear after Commands.
EOF

bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile-file "$TMP/t76-profile.yaml" \
  --target "$TMP/t76" \
  > /dev/null 2>&1

assert_file_exists "$TMP/t76/AGENTS.md" "T76"
assert_file_contains "$TMP/t76/AGENTS.md" "<!-- local override: AGENTS.local.md -->" "T76"
assert_file_contains "$TMP/t76/AGENTS.md" "## Post-Commands Section" "T76"

# T77 — compose: no AGENTS.local.md, no leftover placeholder
run_test "T77 — compose: no AGENTS.local.md produces clean output"
mkdir -p "$TMP/t77"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t77" \
  > /dev/null 2>&1

assert_file_not_contains "$TMP/t77/AGENTS.md" "<!-- local override:" "T77"

# T78 — compose: nested mode with root AGENTS.local.md in root only
run_test "T78 — compose: nested mode root AGENTS.local.md in root only"
mkdir -p "$TMP/t78"
cat > "$TMP/t78/AGENTS.local.md" <<'EOF'
## Root Custom Rules

These are root-level custom rules.
EOF

bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-nuxt-vite-ui \
  --target "$TMP/t78" \
  > /dev/null 2>&1

assert_file_exists "$TMP/t78/AGENTS.md" "T78"
assert_file_contains "$TMP/t78/AGENTS.md" "## Root Custom Rules" "T78"
# Should NOT appear in tier files
assert_file_not_contains "$TMP/t78/backend/AGENTS.md" "Root Custom Rules" "T78"
assert_file_not_contains "$TMP/t78/ui/AGENTS.md" "Root Custom Rules" "T78"

# T79 — compose: nested mode with tier-level AGENTS.local.md
run_test "T79 — compose: nested mode tier-level AGENTS.local.md"
mkdir -p "$TMP/t79"
mkdir -p "$TMP/t79/backend"
cat > "$TMP/t79/backend/AGENTS.local.md" <<'EOF'
## Backend Custom Rules

These are backend-tier specific rules.
EOF

bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-nuxt-vite-ui \
  --target "$TMP/t79" \
  > /dev/null 2>&1

assert_file_exists "$TMP/t79/AGENTS.md" "T79"
assert_file_not_contains "$TMP/t79/AGENTS.md" "Backend Custom Rules" "T79"
assert_file_exists "$TMP/t79/backend/AGENTS.md" "T79"
assert_file_contains "$TMP/t79/backend/AGENTS.md" "## Backend Custom Rules" "T79"

# T80 — validate: warning when custom_rules declared but AGENTS.local.md absent
run_test "T80 — validate: warning for custom_rules without AGENTS.local.md"
mkdir -p "$TMP/t80"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t80" \
  > /dev/null 2>&1 || true

# Manually add custom_rules to the profile (simulating profile change)
yq -i '.output.custom_rules = {"placement": "append"}' "$TMP/t80/.agentic/profile.yaml" || true

T80_OUTPUT=$(bash "$VALIDATE" \
  --library "$LIBRARY" \
  --target "$TMP/t80" \
  2>&1) || true

assert_stdout_contains "$T80_OUTPUT" "[WARN]" "T80"

# T81 — --import=adopt migrates user-authored AGENTS.md to AGENTS.local.md
run_test "T81 — --import=adopt migrates user-authored AGENTS.md"
mkdir -p "$TMP/t81"
cat > "$TMP/t81/AGENTS.md" <<'EOF'
# Agent Instructions — my-project

## Custom Workflow

My existing custom rules.
EOF

bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t81" \
  --import adopt \
  > /dev/null 2>&1

assert_file_exists "$TMP/t81/AGENTS.local.md" "T81"
assert_file_contains "$TMP/t81/AGENTS.local.md" "## Custom Workflow" "T81"

# T82 — --import=adopt with existing AGENTS.local.md skips migration
run_test "T82 — --import=adopt skips when AGENTS.local.md exists"
mkdir -p "$TMP/t82"
cat > "$TMP/t82/AGENTS.md" <<'EOF'
# Agent Instructions

Old content.
EOF
cat > "$TMP/t82/AGENTS.local.md" <<'EOF'
## Existing Local Rules

These are my local rules.
EOF

bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t82" \
  --import adopt \
  > /dev/null 2>&1

# AGENTS.local.md should NOT be overwritten
assert_file_contains "$TMP/t82/AGENTS.local.md" "## Existing Local Rules" "T82"
# AGENTS.md should be generated, overwriting old content
assert_file_contains "$TMP/t82/AGENTS.md" "<!-- AUTO-GENERATED by agentic library -->" "T82"

# T83 — --import=skip aborts on user-authored AGENTS.md
run_test "T83 — --import=skip exits with error on user-authored AGENTS.md"
mkdir -p "$TMP/t83"
cat > "$TMP/t83/AGENTS.md" <<'EOF'
# Agent Instructions

My custom rules without marker.
EOF

T83_EXIT=0
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t83" \
  --import skip \
  > /dev/null 2>&1 || T83_EXIT=$?

assert_exit_code 1 "$T83_EXIT" "T83"

# T84 — --import=overwrite --yes overwrites without prompt
run_test "T84 — --import=overwrite --yes overwrites without prompt"
mkdir -p "$TMP/t84"
cat > "$TMP/t84/AGENTS.md" <<'EOF'
# Agent Instructions

Old user content.
EOF

T84_EXIT=0
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t84" \
  --import overwrite \
  --yes \
  > /dev/null 2>&1 || T84_EXIT=$?

assert_exit_code 0 "$T84_EXIT" "T84"
assert_file_contains "$TMP/t84/AGENTS.md" "<!-- AUTO-GENERATED by agentic library -->" "T84"
assert_file_not_contains "$TMP/t84/AGENTS.md" "Old user content" "T84"

# T85 — compose: after_section fallback when heading not found emits warning to stderr
run_test "T85 — compose: after_section fallback emits warning"
mkdir -p "$TMP/t85"
cat > "$TMP/t85-profile.yaml" <<'EOF'
meta:
  name: Test After Section Fallback
  description: Test profile with after_section placement
  version: "1.0.0"
fragments:
  base:
    - git-conventions
output:
  build_command: ""
  test_command: ""
  lint_command: ""
  custom_rules:
    placement: after_section
    after_section: "NonExistentSection"
vendors:
  enabled: []
EOF

cat > "$TMP/t85/AGENTS.local.md" <<'EOF'
## Custom Section

This should appear after a missing section.
EOF

T85_EXIT=0
T85_OUTPUT=$(bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile-file "$TMP/t85-profile.yaml" \
  --target "$TMP/t85" \
  2>&1) || T85_EXIT=$?

# Check exit was successful
assert_exit_code 0 "$T85_EXIT" "T85"
# Check warning was emitted (captured in combined stdout/stderr)
if echo "$T85_OUTPUT" | grep -q "Warning.*NonExistentSection.*not found"; then
  pass "T85 — warning emitted for missing section"
else
  fail "T85 — should emit warning for missing section"
fi
# Check content was appended (not lost)
assert_file_contains "$TMP/t85/AGENTS.md" "## Custom Section" "T85"

# T86 — compose: --import=adopt in nested mode migrates root AGENTS.md
run_test "T86 — compose: --import=adopt works in nested mode"
mkdir -p "$TMP/t86"
cat > "$TMP/t86/AGENTS.md" <<'EOF'
# Agent Instructions — my-project

## Custom Workflow

My existing custom rules.
EOF

bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-nuxt-vite-ui \
  --target "$TMP/t86" \
  --import adopt \
  > /dev/null 2>&1

assert_file_exists "$TMP/t86/AGENTS.local.md" "T86"
assert_file_contains "$TMP/t86/AGENTS.local.md" "## Custom Workflow" "T86"
# Original AGENTS.md should be regenerated (not user-authored anymore)
assert_file_contains "$TMP/t86/AGENTS.md" "<!-- AUTO-GENERATED by agentic library -->" "T86"

# T87 — compose: Mode B with --import=skip does NOT abort (auto-generated AGENTS.md)
run_test "T87 — compose: --import=skip with auto-generated AGENTS.md proceeds"
mkdir -p "$TMP/t87"
# First compose to create an auto-generated AGENTS.md
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t87" \
  > /dev/null 2>&1

# Now run compose again with --import=skip (should succeed since AGENTS.md is auto-generated)
T87_EXIT=0
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t87" \
  --import skip \
  > /dev/null 2>&1 || T87_EXIT=$?

assert_exit_code 0 "$T87_EXIT" "T87"

# T88 — compose: empty AGENTS.local.md produces no override block
run_test "T88 — compose: empty AGENTS.local.md produces clean output"
mkdir -p "$TMP/t88"
# Create empty file
touch "$TMP/t88/AGENTS.local.md"

bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t88" \
  > /dev/null 2>&1

assert_file_not_contains "$TMP/t88/AGENTS.md" "<!-- local override" "T88"

# T89 — compose: profile import_strategy: skip exits 1 without --import flag on user-authored AGENTS.md
run_test "T89 — compose: profile import_strategy: skip exits 1"
mkdir -p "$TMP/t89"
cat > "$TMP/t89/AGENTS.md" <<'EOF'
# Agent Instructions

User-authored content without marker.
EOF

cat > "$TMP/t89-profile.yaml" <<'EOF'
meta:
  name: Test Skip Strategy
  description: Test profile with skip import strategy
  version: "1.0.0"
fragments:
  base:
    - git-conventions
output:
  build_command: ""
  test_command: ""
  lint_command: ""
  custom_rules:
    import_strategy: skip
vendors:
  enabled: []
EOF

T89_EXIT=0
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile-file "$TMP/t89-profile.yaml" \
  --target "$TMP/t89" \
  > /dev/null 2>&1 || T89_EXIT=$?

assert_exit_code 1 "$T89_EXIT" "T89"

# T90 — vendor-gen: gemini creates GEMINI.md in vendor-files (lean mode)
run_test "T90 — vendor-gen: gemini creates GEMINI.md with project name header"
mkdir -p "$TMP/t90"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-microservice \
  --target "$TMP/t90" \
  > /dev/null 2>&1

bash "$VENDOR_GEN" \
  --library "$LIBRARY" \
  --target "$TMP/t90" \
  --vendors gemini \
  > /dev/null 2>&1

assert_file_exists "$TMP/t90/.agentic/vendor-files/gemini/GEMINI.md" "T90 GEMINI.md"
assert_file_contains "$TMP/t90/.agentic/vendor-files/gemini/GEMINI.md" "typescript-hexagonal-microservice" "T90 project name"

# T91 — vendor-gen: gemini creates system.md in vendor-files (lean mode)
run_test "T91 — vendor-gen: gemini creates system.md in vendor-files"
assert_file_exists "$TMP/t90/.agentic/vendor-files/gemini/system.md" "T91 system.md"

# T92 — vendor-gen: gemini GEMINI.md contains fragment content
run_test "T92 — vendor-gen: gemini GEMINI.md contains fragment content"
assert_file_contains "$TMP/t90/.agentic/vendor-files/gemini/GEMINI.md" "## Git Conventions" "T92 fragment content"

# T93 — vendor-switch: GEMINI.md root symlink created after switching to gemini
run_test "T93 — vendor-switch: GEMINI.md root symlink created"
mkdir -p "$TMP/t93"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t93" \
  > /dev/null 2>&1

bash "$VENDOR_GEN" \
  --library "$LIBRARY" \
  --target "$TMP/t93" \
  --vendors gemini \
  > /dev/null 2>&1

bash "$VENDOR_SWITCH" \
  --library "$LIBRARY" \
  --target "$TMP/t93" \
  gemini \
  > /dev/null 2>&1

assert_symlink_exists "$TMP/t93/GEMINI.md" "T93 GEMINI.md symlink"

# T94 — vendor-switch: .gemini/system.md symlink created after switching to gemini
run_test "T94 — vendor-switch: .gemini/system.md symlink created"
assert_symlink_exists "$TMP/t93/.gemini/system.md" "T94 .gemini/system.md symlink"

# T95 — vendor-switch: .gemini/skills symlink created when skills exist
run_test "T95 — vendor-switch: .gemini/skills symlink created when skills exist"
bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t93" \
  --skills code-review \
  > /dev/null 2>&1

# Re-switch to gemini to create skills symlink
bash "$VENDOR_SWITCH" \
  --library "$LIBRARY" \
  --target "$TMP/t93" \
  gemini \
  > /dev/null 2>&1

assert_symlink_exists "$TMP/t93/.gemini/skills" "T95 .gemini/skills symlink"

# T96 — deploy-skills: .gemini/skills symlink created with --vendor gemini
run_test "T96 — deploy-skills: .gemini/skills symlink created with --vendor gemini"
mkdir -p "$TMP/t96"
bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t96" \
  --skills code-review \
  --vendor gemini \
  > /dev/null 2>&1

assert_symlink_exists "$TMP/t96/.gemini/skills" "T96 .gemini/skills symlink"

# T97 — vendor isolation: vendors/gemini.sh exists and is a regular file
run_test "T97 — vendor isolation: vendors/gemini.sh exists"
if [[ -f "$LIBRARY/tooling/lib/vendors/gemini.sh" ]]; then
  pass "T97 — vendors/gemini.sh exists"
else
  fail "T97 — vendors/gemini.sh should exist"
fi

# T98 — vendor isolation: vendors/claude.sh exists and is a regular file
run_test "T98 — vendor isolation: vendors/claude.sh exists"
if [[ -f "$LIBRARY/tooling/lib/vendors/claude.sh" ]]; then
  pass "T98 — vendors/claude.sh exists"
else
  fail "T98 — vendors/claude.sh should exist"
fi

# T99 — init: creates .agentic skeleton files
run_test "T99 — init: creates .agentic skeleton"
mkdir -p "$TMP/t99"
AGENTIC_REPO_ROOT="$LIBRARY" "$CLI" init "$TMP/t99" --no-sync > /dev/null 2>&1
assert_file_exists "$TMP/t99/.agentic/config.yaml" "T99 config"
assert_file_exists "$TMP/t99/.agentic/profile.yaml" "T99 profile"
assert_file_exists "$TMP/t99/.agentic/mcp.yaml" "T99 mcp"
if [[ -d "$TMP/t99/.agentic/project-skills" ]]; then
  pass "T99 project-skills directory exists"
else
  fail "T99 project-skills directory should exist"
fi

# T100 — init: generated YAML files include schema annotation headers
run_test "T100 — init: YAML schema headers are present"
assert_file_contains "$TMP/t99/.agentic/config.yaml" "# yaml-language-server: \$schema=https://raw.githubusercontent.com/soulcodex/agentic/main/schemas/config.schema.json" "T100 config schema"
assert_file_contains "$TMP/t99/.agentic/profile.yaml" "# yaml-language-server: \$schema=https://raw.githubusercontent.com/soulcodex/agentic/main/schemas/profile.schema.json" "T100 profile schema"
assert_file_contains "$TMP/t99/.agentic/mcp.yaml" "# yaml-language-server: \$schema=https://raw.githubusercontent.com/soulcodex/agentic/main/schemas/mcp.schema.json" "T100 mcp schema"

# T101 — init --sync: scaffolds and composes immediately
run_test "T101 — init --sync composes project"
mkdir -p "$TMP/t101"
AGENTIC_REPO_ROOT="$LIBRARY" "$CLI" init "$TMP/t101" --sync > /dev/null 2>&1
assert_file_exists "$TMP/t101/AGENTS.md" "T101 AGENTS"
assert_file_contains "$TMP/t101/AGENTS.md" "<!-- AUTO-GENERATED by agentic library -->" "T101 generated marker"

# T102 — compose: .agentic/mcp.yaml takes precedence over legacy profile mcp
run_test "T102 — compose: mcp.yaml precedence"
mkdir -p "$TMP/t102/.agentic"
cat > "$TMP/t102/.agentic/mcp.yaml" <<'EOF'
strategy: merge
servers:
  file-server:
    type: stdio
    command: npx
    args:
      - -y
      - "@modelcontextprotocol/server-filesystem"
EOF
cat > "$TMP/t102-profile.yaml" <<'EOF'
meta:
  name: Test MCP Precedence
  description: Test mcp precedence
  version: "1.0.0"
fragments:
  base:
    - git-conventions
output:
  build_command: ""
  test_command: ""
  lint_command: ""
vendors:
  enabled: []
mcp:
  strategy: merge
  servers:
    legacy-server:
      type: stdio
      command: legacy-cmd
      args: ["--legacy"]
EOF
T102_EXIT=0
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile-file "$TMP/t102-profile.yaml" \
  --target "$TMP/t102" \
  > /dev/null 2>&1 || T102_EXIT=$?
assert_exit_code 0 "$T102_EXIT" "T102"
assert_file_exists "$TMP/t102/.mcp.json" "T102 mcp json"
assert_file_contains "$TMP/t102/.mcp.json" "file-server" "T102 file server present"
assert_file_not_contains "$TMP/t102/.mcp.json" "legacy-server" "T102 legacy server ignored"

# T103 — compose: legacy profile mcp still works with deprecation warning
run_test "T103 — compose: legacy profile mcp fallback warning"
mkdir -p "$TMP/t103"
cat > "$TMP/t103-profile.yaml" <<'EOF'
meta:
  name: Test Legacy MCP
  description: Test legacy mcp fallback
  version: "1.0.0"
fragments:
  base:
    - git-conventions
output:
  build_command: ""
  test_command: ""
  lint_command: ""
vendors:
  enabled: []
mcp:
  strategy: merge
  servers:
    legacy-only:
      type: stdio
      command: legacy-mcp
      args: ["--ok"]
EOF
T103_EXIT=0
T103_OUTPUT=$(bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile-file "$TMP/t103-profile.yaml" \
  --target "$TMP/t103" \
  2>&1) || T103_EXIT=$?
assert_exit_code 0 "$T103_EXIT" "T103"
assert_stdout_contains "$T103_OUTPUT" "Deprecated MCP declaration in profile detected" "T103 warning"
assert_file_exists "$TMP/t103/.mcp.json" "T103 mcp json"
assert_file_contains "$TMP/t103/.mcp.json" "legacy-only" "T103 legacy server seeded"

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "────────────────────────────────────────"
TOTAL=$((PASS + FAIL))
echo "Results: $PASS/$TOTAL passed"
if [[ "$FAIL" -gt 0 ]]; then
  echo "FAILED: $FAIL test(s)"
  exit 1
else
  echo "All tests passed."
fi
