#!/bin/bash
# test.sh — Integration test suite for the agentic library tooling
# Called by: just test
set -euo pipefail

# ── Argument parsing ──────────────────────────────────────────────────────────
LIBRARY=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --library) LIBRARY="$2"; shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

[[ -z "$LIBRARY" ]] && { echo "Error: --library required" >&2; exit 1; }

# ── Setup ─────────────────────────────────────────────────────────────────────
COMPOSE="$LIBRARY/tooling/lib/compose.sh"
VALIDATE="$LIBRARY/tooling/lib/validate.sh"
VENDOR_GEN="$LIBRARY/tooling/lib/vendor-gen.sh"
VENDOR_SWITCH="$LIBRARY/tooling/lib/vendor-switch.sh"
DEPLOY_SKILLS="$LIBRARY/tooling/lib/deploy-skills.sh"
LINT="$LIBRARY/tooling/lib/lint.sh"
INDEX="$LIBRARY/tooling/lib/index.sh"

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

PASS=0
FAIL=0

# ── Test helpers ──────────────────────────────────────────────────────────────
pass() { echo "  [PASS] $*"; PASS=$((PASS + 1)); }
fail() { echo "  [FAIL] $*"; FAIL=$((FAIL + 1)); }

assert_file_exists() {
  local file="$1" label="$2"
  if [[ -f "$file" ]]; then
    pass "$label — file exists: $file"
  else
    fail "$label — expected file does not exist: $file"
  fi
}

assert_file_not_exists() {
  local file="$1" label="$2"
  if [[ ! -e "$file" ]]; then
    pass "$label — path does not exist (as expected): $file"
  else
    fail "$label — path should not exist but does: $file"
  fi
}

assert_file_contains() {
  local file="$1" pattern="$2" label="$3"
  if grep -qF "$pattern" "$file" 2>/dev/null; then
    pass "$label — contains: $pattern"
  else
    fail "$label — missing pattern in $file: $pattern"
  fi
}

assert_file_not_contains() {
  local file="$1" pattern="$2" label="$3"
  if ! grep -qF "$pattern" "$file" 2>/dev/null; then
    pass "$label — does not contain: $pattern"
  else
    fail "$label — unexpected pattern found in $file: $pattern"
  fi
}

assert_exit_code() {
  local expected="$1" actual="$2" label="$3"
  if [[ "$actual" -eq "$expected" ]]; then
    pass "$label — exit code $expected"
  else
    fail "$label — expected exit code $expected, got $actual"
  fi
}

assert_stdout_contains() {
  local output="$1" pattern="$2" label="$3"
  if echo "$output" | grep -qF -- "$pattern"; then
    pass "$label — stdout contains: $pattern"
  else
    fail "$label — stdout missing: $pattern"
  fi
}

assert_json_valid() {
  local file="$1" label="$2"
  if jq . "$file" > /dev/null 2>&1; then
    pass "$label — valid JSON: $file"
  else
    fail "$label — invalid JSON: $file"
  fi
}

assert_json_min_count() {
  local file="$1" jq_expr="$2" min="$3" label="$4"
  local count
  count=$(jq "$jq_expr" "$file" 2>/dev/null || echo 0)
  if [[ "$count" -ge "$min" ]]; then
    pass "$label — count $count >= $min"
  else
    fail "$label — count $count < $min (in $file)"
  fi
}

run_test() {
  local name="$1"
  echo ""
  echo "── $name"
}

# ── Tests ─────────────────────────────────────────────────────────────────────

# T01 — compose: typescript-hexagonal-microservice (lean default)
run_test "T01 — compose: typescript-hexagonal-microservice (lean)"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-microservice \
  --target "$TMP/t01" \
  > /dev/null 2>&1

assert_file_exists "$TMP/t01/AGENTS.md" "T01"
assert_file_contains "$TMP/t01/AGENTS.md" "<!-- AUTO-GENERATED by agentic library -->" "T01"
assert_file_contains "$TMP/t01/AGENTS.md" "## Conventions & Patterns" "T01"
assert_file_contains "$TMP/t01/AGENTS.md" ".agentic/fragments/git-conventions.md" "T01"
assert_file_contains "$TMP/t01/AGENTS.md" ".agentic/fragments/typescript.md" "T01"
assert_file_not_contains "$TMP/t01/AGENTS.md" "Conventional Commits" "T01"
assert_file_exists "$TMP/t01/.agentic/config.yaml" "T01"

# T02 — compose: go-hexagonal-microservice (lean default)
run_test "T02 — compose: go-hexagonal-microservice (lean)"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile go-hexagonal-microservice \
  --target "$TMP/t02" \
  > /dev/null 2>&1

assert_file_contains "$TMP/t02/AGENTS.md" ".agentic/fragments/go.md" "T02"
assert_file_not_contains "$TMP/t02/AGENTS.md" ".agentic/fragments/typescript.md" "T02"
assert_file_not_contains "$TMP/t02/AGENTS.md" "explicit error handling" "T02"

# T03 — compose: dry-run produces stdout, no files written
run_test "T03 — compose: dry-run produces stdout, no files written"
DRY_TMPFILE=$(mktemp "$TMP/dry-XXXXXX")
T03_EXIT=0
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-microservice \
  --target "$TMP/t03" \
  --dry-run > "$DRY_TMPFILE" 2>/dev/null || T03_EXIT=$?

assert_exit_code 0 "$T03_EXIT" "T03"
assert_file_not_exists "$TMP/t03" "T03"
assert_file_contains "$DRY_TMPFILE" "## Conventions & Patterns" "T03"

# T04 — compose: unknown profile fails with exit code 1
run_test "T04 — compose: unknown profile fails"
T04_EXIT=0
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile nonexistent-profile \
  --target "$TMP/t04" \
  > /dev/null 2>&1 || T04_EXIT=$?

assert_exit_code 1 "$T04_EXIT" "T04"

# T05 — validate: passes on correctly composed output
run_test "T05 — validate: passes on correctly composed output"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-microservice \
  --target "$TMP/t05" \
  > /dev/null 2>&1

T05_EXIT=0
bash "$VALIDATE" \
  --library "$LIBRARY" \
  --target "$TMP/t05" \
  > /dev/null 2>&1 || T05_EXIT=$?

assert_exit_code 0 "$T05_EXIT" "T05"

# T06 — validate: fails when AGENTS.md is missing
run_test "T06 — validate: fails when AGENTS.md is missing"
mkdir -p "$TMP/t06-empty"
T06_EXIT=0
bash "$VALIDATE" \
  --library "$LIBRARY" \
  --target "$TMP/t06-empty" \
  > /dev/null 2>&1 || T06_EXIT=$?

assert_exit_code 1 "$T06_EXIT" "T06"

# T07 — validate: fails when AGENTS.md has unfilled tokens
run_test "T07 — validate: fails when AGENTS.md has unfilled tokens"
mkdir -p "$TMP/t07"
cat > "$TMP/t07/AGENTS.md" <<'EOF'
# Agent Instructions — test-project

<!-- AUTO-GENERATED by agentic library -->

## Git Conventions

Follow conventional commits.

## Project Setup

Project owner: {{UNFILLED_TOKEN}}
EOF

T07_EXIT=0
bash "$VALIDATE" \
  --library "$LIBRARY" \
  --target "$TMP/t07" \
  > /dev/null 2>&1 || T07_EXIT=$?

assert_exit_code 1 "$T07_EXIT" "T07"

# T08 — vendor-gen: claude creates CLAUDE.md in vendor-files
run_test "T08 — vendor-gen: claude creates CLAUDE.md in vendor-files"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-microservice \
  --target "$TMP/t08" \
  > /dev/null 2>&1

bash "$VENDOR_GEN" \
  --library "$LIBRARY" \
  --target "$TMP/t08" \
  --vendors claude \
  > /dev/null 2>&1

assert_file_exists "$TMP/t08/.agentic/vendor-files/claude/CLAUDE.md" "T08"

# T09 — vendor-gen: copilot creates copilot-instructions.md in vendor-files
run_test "T09 — vendor-gen: copilot creates copilot-instructions.md in vendor-files"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-microservice \
  --target "$TMP/t09" \
  > /dev/null 2>&1

bash "$VENDOR_GEN" \
  --library "$LIBRARY" \
  --target "$TMP/t09" \
  --vendors copilot \
  > /dev/null 2>&1

assert_file_exists "$TMP/t09/.agentic/vendor-files/copilot/copilot-instructions.md" "T09"

# T10 — vendor-gen: gemini creates systemPrompt.md in vendor-files
run_test "T10 — vendor-gen: gemini creates systemPrompt.md in vendor-files"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-microservice \
  --target "$TMP/t10" \
  > /dev/null 2>&1

bash "$VENDOR_GEN" \
  --library "$LIBRARY" \
  --target "$TMP/t10" \
  --vendors gemini \
  > /dev/null 2>&1

assert_file_exists "$TMP/t10/.agentic/vendor-files/gemini/systemPrompt.md" "T10"

# T11 — vendor-gen: fails without AGENTS.md
run_test "T11 — vendor-gen: fails without AGENTS.md"
mkdir -p "$TMP/t11-empty"
T11_EXIT=0
bash "$VENDOR_GEN" \
  --library "$LIBRARY" \
  --target "$TMP/t11-empty" \
  --vendors claude \
  > /dev/null 2>&1 || T11_EXIT=$?

assert_exit_code 1 "$T11_EXIT" "T11"

# T12 — deploy-skills: all skills deployed to canonical .agentic/skills/
run_test "T12 — deploy-skills: all skills deployed to .agentic/skills/"
mkdir -p "$TMP/t12"
bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t12" \
  --skills all \
  > /dev/null 2>&1

assert_file_exists "$TMP/t12/.agentic/skills/code-review/SKILL.md" "T12"
assert_file_exists "$TMP/t12/.agentic/skills/add-tests/SKILL.md" "T12"
assert_file_exists "$TMP/t12/.agentic/skills/README.md" "T12"

# T13 — deploy-skills: selective deployment to .agentic/skills/
run_test "T13 — deploy-skills: selective deployment"
mkdir -p "$TMP/t13"
bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t13" \
  --skills code-review,write-adr \
  > /dev/null 2>&1

assert_file_exists "$TMP/t13/.agentic/skills/code-review/SKILL.md" "T13"
assert_file_exists "$TMP/t13/.agentic/skills/write-adr/SKILL.md" "T13"
assert_file_not_exists "$TMP/t13/.agentic/skills/fix-bug" "T13"

# T14 — lint: passes on the library itself
run_test "T14 — lint: passes on the library itself"
T14_EXIT=0
bash "$LINT" \
  --library "$LIBRARY" \
  > /dev/null 2>&1 || T14_EXIT=$?

assert_exit_code 0 "$T14_EXIT" "T14"

# T15 — index: produces valid JSON with expected counts
run_test "T15 — index: produces valid JSON"
bash "$INDEX" \
  --library "$LIBRARY" \
  > /dev/null 2>&1

assert_json_valid "$LIBRARY/index/skills.json" "T15"
assert_json_valid "$LIBRARY/index/fragments.json" "T15"
assert_json_min_count "$LIBRARY/index/skills.json" '.skills | length' 10 "T15 skills"
assert_json_min_count "$LIBRARY/index/fragments.json" '.fragments | length' 19 "T15 fragments"

# T16 — compose: profile with tech_stack produces ## Technical Stack section
run_test "T16 — compose: tech_stack profile produces ## Technical Stack"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t16" \
  > /dev/null 2>&1

assert_file_contains "$TMP/t16/AGENTS.md" "## Technical Stack" "T16"
assert_file_contains "$TMP/t16/AGENTS.md" "Go 1.23+" "T16"
assert_file_contains "$TMP/t16/AGENTS.md" "Cobra + Viper" "T16"

# T17 — compose: profile with skills produces slim ## Skills listing
run_test "T17 — compose: skills profile produces ## Skills listing"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t17" \
  > /dev/null 2>&1

assert_file_contains "$TMP/t17/AGENTS.md" "## Skills" "T17"
assert_file_contains "$TMP/t17/AGENTS.md" "Load the relevant skill file before starting the task." "T17"
assert_file_contains "$TMP/t17/AGENTS.md" "code-review" "T17"
assert_file_contains "$TMP/t17/AGENTS.md" "write-adr" "T17"

# T18 — compose: --full writes AGENTS.md with inline fragment content
run_test "T18 — compose: --full inlines fragments into AGENTS.md"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t18" \
  --full \
  > /dev/null 2>&1

assert_file_exists "$TMP/t18/AGENTS.md" "T18"
assert_file_contains "$TMP/t18/AGENTS.md" "## Git Conventions" "T18"
assert_file_contains "$TMP/t18/AGENTS.md" "## Go" "T18"
assert_file_exists "$TMP/t18/.agentic/config.yaml" "T18"
assert_file_not_exists "$TMP/t18/.agentic/fragments" "T18"

# T19 — compose: --full embeds skill content inline (not just listing)
run_test "T19 — compose: --full embeds full skill content"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t19" \
  --full \
  > /dev/null 2>&1

assert_file_contains "$TMP/t19/AGENTS.md" "## Skills" "T19"
assert_file_contains "$TMP/t19/AGENTS.md" "## Code Review Skill" "T19"
assert_file_not_contains "$TMP/t19/AGENTS.md" "Load the relevant skill file before starting the task." "T19"

# T20 — compose: profile without tech_stack has no ## Technical Stack; has ## Skills with relational-database-design
run_test "T20 — compose: profile without tech_stack omits that section; skills section present"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile go-hexagonal-microservice \
  --target "$TMP/t20" \
  > /dev/null 2>&1

assert_file_not_contains "$TMP/t20/AGENTS.md" "## Technical Stack"        "T20"
assert_file_contains     "$TMP/t20/AGENTS.md" "## Skills"                  "T20"
assert_file_contains     "$TMP/t20/AGENTS.md" "relational-database-design" "T20"

# T21 — compose: --full produces monolithic AGENTS.md with mode: full in lock file
run_test "T21 — compose: --full flag produces monolithic AGENTS.md"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t21" \
  --full \
  > /dev/null 2>&1

assert_file_exists "$TMP/t21/AGENTS.md" "T21"
assert_file_contains "$TMP/t21/AGENTS.md" "## Git Conventions" "T21"
assert_file_exists "$TMP/t21/.agentic/config.yaml" "T21"
assert_file_contains "$TMP/t21/.agentic/config.yaml" "mode: full" "T21"
assert_file_not_exists "$TMP/t21/.agentic/fragments" "T21"

# T22 — compose: lean default copies fragment files to target
run_test "T22 — compose: lean mode copies fragment files to .agentic/fragments/"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t22" \
  > /dev/null 2>&1

assert_file_exists "$TMP/t22/.agentic/fragments/git-conventions.md" "T22"
assert_file_exists "$TMP/t22/.agentic/fragments/go.md" "T22"
assert_file_exists "$TMP/t22/.agentic/fragments/cobra.md" "T22"
assert_file_contains "$TMP/t22/.agentic/config.yaml" "mode: lean" "T22"

# T23 — vendor-gen: copilot instructions are fully populated in lean mode
run_test "T23 — vendor-gen: copilot instructions contain fragment content in lean mode"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t23" \
  > /dev/null 2>&1

bash "$VENDOR_GEN" \
  --library "$LIBRARY" \
  --target "$TMP/t23" \
  --vendors copilot \
  > /dev/null 2>&1

assert_file_exists "$TMP/t23/.agentic/vendor-files/copilot/copilot-instructions.md" "T23"
assert_file_contains "$TMP/t23/.agentic/vendor-files/copilot/copilot-instructions.md" "Conventional Commits" "T23"
assert_file_contains "$TMP/t23/.agentic/vendor-files/copilot/copilot-instructions.md" "Git Conventions" "T23"

# T24 — compose: nested mode produces root AGENTS.md with tier table
run_test "T24 — compose: nested mode root AGENTS.md has Tiers section"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-nuxt-vite-ui \
  --target "$TMP/t24" > /dev/null 2>&1

assert_file_exists        "$TMP/t24/AGENTS.md"                                          "T24"
assert_file_contains      "$TMP/t24/AGENTS.md" "## Conventions & Patterns"              "T24"
assert_file_contains      "$TMP/t24/AGENTS.md" "## Tiers"                               "T24"
assert_file_contains      "$TMP/t24/AGENTS.md" "backend/AGENTS.md"                      "T24"
assert_file_contains      "$TMP/t24/AGENTS.md" "ui/AGENTS.md"                           "T24"
assert_file_contains      "$TMP/t24/AGENTS.md" ".agentic/fragments/tdd.md"              "T24"
assert_file_not_contains  "$TMP/t24/AGENTS.md" ".agentic/fragments/hexagonal.md"        "T24"
assert_file_not_contains  "$TMP/t24/AGENTS.md" ".agentic/fragments/vue.md"              "T24"
assert_file_contains      "$TMP/t24/.agentic/config.yaml" "structure: nested"           "T24"
assert_file_contains      "$TMP/t24/.agentic/config.yaml" "mode: lean"                  "T24"
assert_file_not_contains  "$TMP/t24/AGENTS.md"            "## Commands"                 "T24"

# T25 — compose: nested lean mode writes correct tier AGENTS.md files
run_test "T25 — compose: nested lean mode tier AGENTS.md content"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-nuxt-vite-ui \
  --target "$TMP/t25" > /dev/null 2>&1

assert_file_exists        "$TMP/t25/backend/AGENTS.md"                                  "T25"
assert_file_exists        "$TMP/t25/ui/AGENTS.md"                                       "T25"
assert_file_contains      "$TMP/t25/backend/AGENTS.md" ".agentic/fragments/typescript.md"  "T25"
assert_file_contains      "$TMP/t25/backend/AGENTS.md" ".agentic/fragments/hexagonal.md"   "T25"
assert_file_not_contains  "$TMP/t25/backend/AGENTS.md" ".agentic/fragments/vue.md"         "T25"
assert_file_not_contains  "$TMP/t25/backend/AGENTS.md" ".agentic/fragments/nuxt.md"        "T25"
assert_file_contains      "$TMP/t25/ui/AGENTS.md"      ".agentic/fragments/vue.md"         "T25"
assert_file_contains      "$TMP/t25/ui/AGENTS.md"      ".agentic/fragments/nuxt.md"        "T25"
assert_file_not_contains  "$TMP/t25/ui/AGENTS.md"      ".agentic/fragments/hexagonal.md"   "T25"
assert_file_not_contains  "$TMP/t25/backend/AGENTS.md" ".agentic/fragments/tdd.md"         "T25"
assert_file_not_contains  "$TMP/t25/ui/AGENTS.md"      ".agentic/fragments/tdd.md"         "T25"
assert_file_exists        "$TMP/t25/.agentic/fragments/hexagonal.md"                    "T25"
assert_file_exists        "$TMP/t25/.agentic/fragments/vue.md"                          "T25"
assert_file_contains      "$TMP/t25/backend/AGENTS.md" "## Commands"                    "T25"
assert_file_contains      "$TMP/t25/ui/AGENTS.md"      "## Commands"                    "T25"

# T26 — compose: nested --full inlines content into tier AGENTS.md files
run_test "T26 — compose: nested --full inlines fragment content in tier files"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-nuxt-vite-ui \
  --target "$TMP/t26" \
  --full > /dev/null 2>&1

assert_file_contains      "$TMP/t26/AGENTS.md"         "## Testing Philosophy"          "T26"
assert_file_not_contains  "$TMP/t26/AGENTS.md"         "## Hexagonal Architecture"      "T26"
assert_file_not_contains  "$TMP/t26/AGENTS.md"         "## Vue 3"                       "T26"
assert_file_contains      "$TMP/t26/backend/AGENTS.md" "## TypeScript"                  "T26"
assert_file_contains      "$TMP/t26/backend/AGENTS.md" "## Hexagonal Architecture"      "T26"
assert_file_not_contains  "$TMP/t26/backend/AGENTS.md" "## Vue 3"                       "T26"
assert_file_contains      "$TMP/t26/ui/AGENTS.md"      "## Vue 3"                       "T26"
assert_file_not_contains  "$TMP/t26/ui/AGENTS.md"      "## Hexagonal Architecture"      "T26"
assert_file_contains      "$TMP/t26/.agentic/config.yaml" "structure: nested"           "T26"

# T27 — compose: proprietary_libraries appear in correct locations
run_test "T27 — compose: proprietary_libraries sections in correct locations"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile typescript-hexagonal-nuxt-vite-ui \
  --target "$TMP/t27" > /dev/null 2>&1

assert_file_contains      "$TMP/t27/AGENTS.md"         "@acme/core"              "T27"
assert_file_contains      "$TMP/t27/AGENTS.md"         "Core domain primitives"  "T27"
assert_file_contains      "$TMP/t27/backend/AGENTS.md" "@acme/domain-kit"        "T27"
assert_file_contains      "$TMP/t27/backend/AGENTS.md" "docs.acme.internal"      "T27"
assert_file_contains      "$TMP/t27/ui/AGENTS.md"      "@acme/ui-tokens"         "T27"
assert_file_not_contains  "$TMP/t27/AGENTS.md"         "@acme/domain-kit"        "T27"
assert_file_not_contains  "$TMP/t27/AGENTS.md"         "@acme/ui-tokens"         "T27"

# T28 — vendor-switch: creates symlinks for the active vendor
run_test "T28 — vendor-switch: symlink-based switching from claude to gemini"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t28" \
  > /dev/null 2>&1

# Deploy skills so we can test skill symlinks
bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t28" \
  --skills code-review \
  > /dev/null 2>&1

# Activate claude vendor
bash "$VENDOR_SWITCH" \
  --library "$LIBRARY" \
  --target "$TMP/t28" \
  claude \
  > /dev/null 2>&1

# Claude should have CLAUDE.md symlink and .claude/skills symlink
assert_file_exists     "$TMP/t28/CLAUDE.md"                                   "T28 claude"
assert_file_exists     "$TMP/t28/.agentic/vendor-files/claude/CLAUDE.md"      "T28 claude"
assert_file_contains   "$TMP/t28/.agentic/config.yaml" "active_vendors:"      "T28 claude"
assert_file_contains   "$TMP/t28/.agentic/config.yaml" "  - claude"           "T28 claude"

# Now switch to gemini
bash "$VENDOR_SWITCH" \
  --library "$LIBRARY" \
  --target "$TMP/t28" \
  gemini \
  > /dev/null 2>&1

# Gemini should have symlink, claude symlinks should be gone
assert_file_exists     "$TMP/t28/.gemini/systemPrompt.md"                      "T28 gemini"
assert_file_exists     "$TMP/t28/.agentic/vendor-files/gemini/systemPrompt.md" "T28 gemini"
assert_file_not_exists "$TMP/t28/CLAUDE.md"                                    "T28 gemini (no claude)"
assert_file_contains   "$TMP/t28/.agentic/config.yaml" "active_vendors:"       "T28 gemini"
assert_file_contains   "$TMP/t28/.agentic/config.yaml" "  - gemini"            "T28 gemini"
# Verify no stash directory exists (old system removed)
assert_file_not_exists "$TMP/t28/.agentic/vendor-stash"                        "T28 no stash"

# T29 — vendor-switch: list subcommand shows all vendors
run_test "T29 — vendor-switch: list subcommand shows all vendors"
T29_TMPFILE=$(mktemp "$TMP/t29-XXXXXX")
bash "$VENDOR_SWITCH" \
  --library "$LIBRARY" \
  --target "$TMP/t28" \
  list > "$T29_TMPFILE" 2>&1 || true

assert_file_contains "$T29_TMPFILE" "claude"   "T29"
assert_file_contains "$T29_TMPFILE" "copilot"  "T29"
assert_file_contains "$T29_TMPFILE" "codex"    "T29"
assert_file_contains "$T29_TMPFILE" "gemini"   "T29"
assert_file_contains "$T29_TMPFILE" "opencode" "T29"

# T30 — deploy-skills: creates vendor skill symlinks when --vendor is specified
run_test "T30 — deploy-skills: creates vendor skill symlinks"
mkdir -p "$TMP/t30"
bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t30" \
  --skills code-review \
  --vendor claude \
  > /dev/null 2>&1

# Should have canonical location and symlink
assert_file_exists "$TMP/t30/.agentic/skills/code-review/SKILL.md" "T30"
# Check .claude/skills is a symlink pointing to ../.agentic/skills
if [[ -L "$TMP/t30/.claude/skills" ]]; then
  pass "T30 — .claude/skills is a symlink"
else
  fail "T30 — .claude/skills should be a symlink"
fi

# T31 — deploy-skills: creates multiple vendor symlinks
run_test "T31 — deploy-skills: creates symlinks for multiple vendors"
mkdir -p "$TMP/t31"
bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t31" \
  --skills code-review \
  --vendor claude,codex,opencode \
  > /dev/null 2>&1

# Check all three vendor symlinks
if [[ -L "$TMP/t31/.claude/skills" ]]; then
  pass "T31 — .claude/skills is a symlink"
else
  fail "T31 — .claude/skills should be a symlink"
fi
if [[ -L "$TMP/t31/.agents/skills" ]]; then
  pass "T31 — .agents/skills is a symlink (codex)"
else
  fail "T31 — .agents/skills should be a symlink"
fi
if [[ -L "$TMP/t31/.opencode/skills" ]]; then
  pass "T31 — .opencode/skills is a symlink"
else
  fail "T31 — .opencode/skills should be a symlink"
fi

# T32 — vendor-switch: creates skill symlinks automatically
run_test "T32 — vendor-switch: creates skill symlinks for codex"
mkdir -p "$TMP/t32"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t32" \
  > /dev/null 2>&1

# Deploy skills first
bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t32" \
  --skills code-review \
  > /dev/null 2>&1

# Switch to codex
bash "$VENDOR_SWITCH" \
  --library "$LIBRARY" \
  --target "$TMP/t32" \
  codex \
  > /dev/null 2>&1

# Codex should have .agents/skills symlink
if [[ -L "$TMP/t32/.agents/skills" ]]; then
  pass "T32 — .agents/skills symlink created for codex"
else
  fail "T32 — .agents/skills should be a symlink for codex"
fi
assert_file_contains "$TMP/t32/.agentic/config.yaml" "active_vendors:" "T32"
assert_file_contains "$TMP/t32/.agentic/config.yaml" "  - codex" "T32"

# T33 — vendor-switch: migration removes old stash directory
run_test "T33 — vendor-switch: migrates from old stash system"
mkdir -p "$TMP/t33"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t33" \
  > /dev/null 2>&1

# Simulate old stash directory
mkdir -p "$TMP/t33/.agentic/vendor-stash/claude"
echo "old file" > "$TMP/t33/.agentic/vendor-stash/claude/CLAUDE.md"

# Run vendor-switch
bash "$VENDOR_SWITCH" \
  --library "$LIBRARY" \
  --target "$TMP/t33" \
  claude \
  > /dev/null 2>&1

# Old stash should be removed
assert_file_not_exists "$TMP/t33/.agentic/vendor-stash" "T33"
# New vendor-files should exist
assert_file_exists "$TMP/t33/.agentic/vendor-files/claude/CLAUDE.md" "T33"

# T34 — skills README contains vendor compatibility table
run_test "T34 — deploy-skills: README contains vendor compatibility info"
mkdir -p "$TMP/t34"
bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t34" \
  --skills code-review \
  > /dev/null 2>&1

assert_file_exists "$TMP/t34/.agentic/skills/README.md" "T34"
assert_file_contains "$TMP/t34/.agentic/skills/README.md" "Vendor Compatibility" "T34"
assert_file_contains "$TMP/t34/.agentic/skills/README.md" ".claude/skills" "T34"
assert_file_contains "$TMP/t34/.agentic/skills/README.md" ".agents/skills" "T34"
assert_file_contains "$TMP/t34/.agentic/skills/README.md" "code-review" "T34"

# ══════════════════════════════════════════════════════════════════════════════
# LOCAL PROFILE SUPPORT TESTS
# ══════════════════════════════════════════════════════════════════════════════

# T35 — compose: copies profile to .agentic/profile.yaml
run_test "T35 — compose: copies profile to .agentic/profile.yaml"
mkdir -p "$TMP/t35"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t35" \
  > /dev/null 2>&1

assert_file_exists "$TMP/t35/.agentic/profile.yaml" "T35"
assert_file_contains "$TMP/t35/.agentic/profile.yaml" "meta:" "T35"

# T36 — compose: --profile-file flag works with local profile
run_test "T36 — compose: --profile-file flag works with local profile"
mkdir -p "$TMP/t36"
# First compose to get a profile
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t36" \
  > /dev/null 2>&1

# Modify the local profile
sed -i.bak 's/version: .*/version: "99.0.0"/' "$TMP/t36/.agentic/profile.yaml"

# Re-compose using local profile
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile-file "$TMP/t36/.agentic/profile.yaml" \
  --target "$TMP/t36" \
  > /dev/null 2>&1

assert_file_contains "$TMP/t36/AGENTS.md" "v99.0.0" "T36"

# T37 — sync.sh: regenerates from local profile
run_test "T37 — sync.sh: regenerates from local profile"
SYNC="$LIBRARY/tooling/lib/sync.sh"
mkdir -p "$TMP/t37"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t37" \
  > /dev/null 2>&1

# Modify the local profile version
sed -i.bak 's/version: .*/version: "88.0.0"/' "$TMP/t37/.agentic/profile.yaml"

# Run sync
bash "$SYNC" --target "$TMP/t37" > /dev/null 2>&1

assert_file_contains "$TMP/t37/AGENTS.md" "v88.0.0" "T37"

# T38 — vendor-switch: sync subcommand works
run_test "T38 — vendor-switch: sync subcommand works"
mkdir -p "$TMP/t38"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t38" \
  > /dev/null 2>&1

# Activate a vendor first
bash "$VENDOR_SWITCH" \
  --library "$LIBRARY" \
  --target "$TMP/t38" \
  claude \
  > /dev/null 2>&1

# Modify the local profile version
sed -i.bak 's/version: .*/version: "77.0.0"/' "$TMP/t38/.agentic/profile.yaml"

# Run sync via vendor-switch
bash "$VENDOR_SWITCH" \
  --library "$LIBRARY" \
  --target "$TMP/t38" \
  sync \
  > /dev/null 2>&1

assert_file_contains "$TMP/t38/AGENTS.md" "v77.0.0" "T38"
# Active vendors should be preserved
assert_file_contains "$TMP/t38/.agentic/config.yaml" "active_vendors:" "T38"
assert_file_contains "$TMP/t38/.agentic/config.yaml" "  - claude" "T38"

# T39 — deploy-skills: project: prefix deploys project-local skills
run_test "T39 — deploy-skills: project: prefix deploys project-local skills"
mkdir -p "$TMP/t39/.agentic/project-skills/my-custom-skill"
cat > "$TMP/t39/.agentic/project-skills/my-custom-skill/SKILL.md" <<'EOF'
---
name: my-custom-skill
description: A project-specific custom skill
version: 1.0.0
tags: [custom]
vendor_support: [claude, opencode]
---
# My Custom Skill

This is a custom project-local skill.
EOF

bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t39" \
  --skills "project:my-custom-skill" \
  > /dev/null 2>&1

assert_file_exists "$TMP/t39/.agentic/skills/my-custom-skill/SKILL.md" "T39"

# T40 — deploy-skills: missing project: skill warns but does not fail
run_test "T40 — deploy-skills: missing project: skill warns but does not fail"
mkdir -p "$TMP/t40"

# Deploy a missing project skill - should warn but exit 0
OUTPUT=$(bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t40" \
  --skills "project:nonexistent-skill" \
  2>&1) || true

if echo "$OUTPUT" | grep -q "Warning:.*nonexistent-skill"; then
  pass "T40 — warns about missing project skill"
else
  fail "T40 — should warn about missing project skill"
fi

# Should NOT have created the skill directory
assert_file_not_exists "$TMP/t40/.agentic/skills/nonexistent-skill" "T40"

# T41 — compose: gitignore entries are added for vendor symlinks
run_test "T41 — compose: gitignore entries for vendor symlinks"
mkdir -p "$TMP/t41"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t41" \
  > /dev/null 2>&1

# Gitignore should exist with vendor symlink entries
assert_file_exists "$TMP/t41/.gitignore" "T41"
assert_file_contains "$TMP/t41/.gitignore" "CLAUDE.md" "T41"
assert_file_contains "$TMP/t41/.gitignore" ".gemini/" "T41"
assert_file_contains "$TMP/t41/.gitignore" ".github/copilot-instructions.md" "T41"

# T42 — deploy: activates the first vendor automatically
run_test "T42 — deploy: activates the first vendor automatically"
mkdir -p "$TMP/t42"
# Simulate what 'just deploy' does: compose + vendor-gen + deploy-skills + vendor-switch
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t42" \
  > /dev/null 2>&1

bash "$VENDOR_GEN" \
  --library "$LIBRARY" \
  --target "$TMP/t42" \
  --vendors opencode \
  > /dev/null 2>&1

bash "$DEPLOY_SKILLS" \
  --library "$LIBRARY" \
  --target "$TMP/t42" \
  --skills code-review \
  --vendor opencode \
  > /dev/null 2>&1

# Activate the vendor (simulating what justfile deploy does)
bash "$VENDOR_SWITCH" \
  --library "$LIBRARY" \
  --target "$TMP/t42" \
  opencode \
  > /dev/null 2>&1

# active_vendors should be set
assert_file_contains "$TMP/t42/.agentic/config.yaml" "active_vendors:" "T42"
assert_file_contains "$TMP/t42/.agentic/config.yaml" "  - opencode" "T42"
# Symlink should exist
if [[ -L "$TMP/t42/.opencode/skills" ]]; then
  pass "T42 — .opencode/skills symlink created"
else
  fail "T42 — .opencode/skills symlink should be created"
fi

# T43 — vendor-switch: multi-vendor activation
run_test "T43 — vendor-switch: multi-vendor activation"
mkdir -p "$TMP/t43"
bash "$COMPOSE" \
  --library "$LIBRARY" \
  --profile golang-hexagonal-cobra-cli \
  --target "$TMP/t43" \
  > /dev/null 2>&1

# Generate vendor files for both
bash "$VENDOR_GEN" \
  --library "$LIBRARY" \
  --target "$TMP/t43" \
  --vendors claude,copilot \
  > /dev/null 2>&1

# Activate multiple vendors using comma-separated format
bash "$VENDOR_SWITCH" \
  --library "$LIBRARY" \
  --target "$TMP/t43" \
  claude,copilot \
  > /dev/null 2>&1

# active_vendors should contain both
assert_file_contains "$TMP/t43/.agentic/config.yaml" "active_vendors:" "T43"
assert_file_contains "$TMP/t43/.agentic/config.yaml" "  - claude" "T43"
assert_file_contains "$TMP/t43/.agentic/config.yaml" "  - copilot" "T43"

# Both vendor symlinks should exist
assert_file_exists "$TMP/t43/CLAUDE.md" "T43 claude symlink"
assert_file_exists "$TMP/t43/.github/copilot-instructions.md" "T43 copilot symlink"

# Now switch to single vendor - should replace the set
bash "$VENDOR_SWITCH" \
  --library "$LIBRARY" \
  --target "$TMP/t43" \
  gemini \
  > /dev/null 2>&1

# Only gemini should be active now
assert_file_contains "$TMP/t43/.agentic/config.yaml" "  - gemini" "T43 replace"
assert_file_not_exists "$TMP/t43/CLAUDE.md" "T43 claude removed"
assert_file_not_exists "$TMP/t43/.github/copilot-instructions.md" "T43 copilot removed"
assert_file_exists "$TMP/t43/.gemini/systemPrompt.md" "T43 gemini active"

# ══════════════════════════════════════════════════════════════════════════════
# GLOBAL CLI TESTS
# ══════════════════════════════════════════════════════════════════════════════

# T44 — CLI: --help shows usage
run_test "T44 — CLI: --help shows usage"
CLI="$LIBRARY/bin/agentic"
T44_OUTPUT=$("$CLI" --help 2>&1) || true

assert_stdout_contains "$T44_OUTPUT" "agentic" "T44"
assert_stdout_contains "$T44_OUTPUT" "Usage:" "T44"
assert_stdout_contains "$T44_OUTPUT" "deploy" "T44"
assert_stdout_contains "$T44_OUTPUT" "compose" "T44"
assert_stdout_contains "$T44_OUTPUT" "switch" "T44"
assert_stdout_contains "$T44_OUTPUT" "sync" "T44"

# T45 — CLI: version command works
run_test "T45 — CLI: version command works"
T45_OUTPUT=$("$CLI" version 2>&1) || true

assert_stdout_contains "$T45_OUTPUT" "agentic version" "T45"

# T46 — CLI: list profiles works
run_test "T46 — CLI: list profiles works"
T46_OUTPUT=$(AGENTIC_REPO_ROOT="$LIBRARY" "$CLI" list profiles 2>&1) || true

assert_stdout_contains "$T46_OUTPUT" "Available profiles:" "T46"
assert_stdout_contains "$T46_OUTPUT" "golang-hexagonal-cobra-cli" "T46"

# T47 — CLI: list vendors works
run_test "T47 — CLI: list vendors works"
T47_OUTPUT=$(AGENTIC_REPO_ROOT="$LIBRARY" "$CLI" list vendors 2>&1) || true

assert_stdout_contains "$T47_OUTPUT" "Supported vendors:" "T47"
assert_stdout_contains "$T47_OUTPUT" "claude" "T47"
assert_stdout_contains "$T47_OUTPUT" "copilot" "T47"
assert_stdout_contains "$T47_OUTPUT" "gemini" "T47"

# ══════════════════════════════════════════════════════════════════════════════
# LIBRARY DISCOVERY TESTS
# ══════════════════════════════════════════════════════════════════════════════

# T48 — CLI: AGENTIC_REPO_ROOT env var is used for library discovery
run_test "T48 — CLI: AGENTIC_REPO_ROOT env var discovery"
T48_OUTPUT=$(AGENTIC_REPO_ROOT="$LIBRARY" "$CLI" list vendors 2>&1) || true

assert_stdout_contains "$T48_OUTPUT" "Supported vendors:" "T48"

# T49 — CLI: AGENTIC_ROOT env var is used as fallback
run_test "T49 — CLI: AGENTIC_ROOT env var fallback"
T49_OUTPUT=$(AGENTIC_ROOT="$LIBRARY" "$CLI" list vendors 2>&1) || true

assert_stdout_contains "$T49_OUTPUT" "Supported vendors:" "T49"

# T50 — CLI: agentic_root from config.yaml is used when no env var
run_test "T50 — CLI: agentic_root from config.yaml discovery"
mkdir -p "$TMP/t50/.agentic"
cat > "$TMP/t50/.agentic/config.yaml" <<CONFIG
agentic_root: "$LIBRARY"
active_vendors: []
CONFIG

# Run from within the target directory
T50_OUTPUT=$(cd "$TMP/t50" && "$CLI" list vendors 2>&1) || true

assert_stdout_contains "$T50_OUTPUT" "Supported vendors:" "T50"

# T51 — CLI: fails with helpful error when no library found
run_test "T51 — CLI: fails when no library found"
mkdir -p "$TMP/t51"

# Run without any env vars or config
T51_EXIT=0
T51_OUTPUT=$(cd "$TMP/t51" && "$CLI" list profiles 2>&1) || T51_EXIT=$?

assert_exit_code 1 "$T51_EXIT" "T51"
assert_stdout_contains "$T51_OUTPUT" "AGENTIC_REPO_ROOT" "T51"

# T52 — CLI: fails when library path doesn't exist
run_test "T52 — CLI: fails when library path doesn't exist"
T52_EXIT=0
T52_OUTPUT=$(AGENTIC_REPO_ROOT="/nonexistent/path" "$CLI" list profiles 2>&1) || T52_EXIT=$?

assert_exit_code 1 "$T52_EXIT" "T52"
assert_stdout_contains "$T52_OUTPUT" "does not exist" "T52"

# ══════════════════════════════════════════════════════════════════════════════
# TARGET AUTO-DETECTION TESTS
# ══════════════════════════════════════════════════════════════════════════════

# T53 — CLI: auto-detects target from current directory
run_test "T53 — CLI: auto-detects target from current directory"
mkdir -p "$TMP/t53/.agentic"
cat > "$TMP/t53/.agentic/config.yaml" <<CONFIG
agentic_root: "$LIBRARY"
profile: "golang-hexagonal-cobra-cli"
active_vendors: []
CONFIG
cat > "$TMP/t53/.agentic/profile.yaml" <<PROFILE
meta:
  name: Test Profile
  version: "1.0.0"
  description: Test
fragments:
  base:
    - git-conventions
PROFILE

# Run sync from within the directory (should auto-detect)
T53_OUTPUT=$(cd "$TMP/t53" && "$CLI" sync 2>&1) || true

assert_stdout_contains "$T53_OUTPUT" "Composed" "T53"

# T54 — CLI: auto-detects target from subdirectory
run_test "T54 — CLI: auto-detects target from subdirectory"
mkdir -p "$TMP/t54/.agentic"
mkdir -p "$TMP/t54/src/deep/nested"
cat > "$TMP/t54/.agentic/config.yaml" <<CONFIG
agentic_root: "$LIBRARY"
profile: "golang-hexagonal-cobra-cli"
active_vendors: []
CONFIG
cat > "$TMP/t54/.agentic/profile.yaml" <<PROFILE
meta:
  name: Test Profile
  version: "1.0.0"
  description: Test
fragments:
  base:
    - git-conventions
PROFILE

# Run sync from a subdirectory (should find config in parent)
T54_OUTPUT=$(cd "$TMP/t54/src/deep/nested" && "$CLI" sync 2>&1) || true

assert_stdout_contains "$T54_OUTPUT" "Composed" "T54"

# T55 — CLI: fails when outside project and no target given
run_test "T55 — CLI: fails when no target and outside project"
T55_EXIT=0
T55_OUTPUT=$(cd "$TMP" && AGENTIC_REPO_ROOT="$LIBRARY" "$CLI" sync 2>&1) || T55_EXIT=$?

assert_exit_code 1 "$T55_EXIT" "T55"
assert_stdout_contains "$T55_OUTPUT" "Cannot auto-detect target" "T55"

# ══════════════════════════════════════════════════════════════════════════════
# INSTALL SCRIPT TESTS
# ══════════════════════════════════════════════════════════════════════════════

# T56 — install.sh: shows usage without arguments
run_test "T56 — install.sh: shows usage without arguments"
INSTALL="$LIBRARY/tooling/lib/install.sh"
T56_OUTPUT=$("$INSTALL" 2>&1) || true

assert_stdout_contains "$T56_OUTPUT" "Usage:" "T56"
assert_stdout_contains "$T56_OUTPUT" "install" "T56"
assert_stdout_contains "$T56_OUTPUT" "uninstall" "T56"

# T57 — remote install.sh: shows help
run_test "T57 — remote install.sh: shows help"
REMOTE_INSTALL="$LIBRARY/install.sh"
T57_OUTPUT=$("$REMOTE_INSTALL" --help 2>&1) || true

assert_stdout_contains "$T57_OUTPUT" "agentic installer" "T57"
assert_stdout_contains "$T57_OUTPUT" "--dir" "T57"
assert_stdout_contains "$T57_OUTPUT" "--global" "T57"
assert_stdout_contains "$T57_OUTPUT" "--branch" "T57"

# ══════════════════════════════════════════════════════════════════════════════
# INDEX STABILITY TESTS
# ══════════════════════════════════════════════════════════════════════════════

# T58 — index.sh: does not update unchanged content
run_test "T58 — index.sh: does not update unchanged content"
T58_OUTPUT=$(bash "$INDEX" --library "$LIBRARY" 2>&1)

assert_stdout_contains "$T58_OUTPUT" "Unchanged: index/skills.json" "T58"
assert_stdout_contains "$T58_OUTPUT" "Unchanged: index/fragments.json" "T58"

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "────────────────────────────────────────"
TOTAL=$((PASS + FAIL))
echo "Results: $PASS/$TOTAL passed"
if [[ "$FAIL" -gt 0 ]]; then
  echo "FAILED: $FAIL test(s)"
  exit 1
else
  echo "All tests passed."
fi
