#!/bin/bash
# validate.sh — Validates an assembled AGENTS.md in a target project
# Called by: just validate <target>
set -euo pipefail

LIBRARY=""
TARGET=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --library) LIBRARY="$2"; shift 2 ;;
    --target)  TARGET="$2";  shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

[[ -z "$TARGET" ]] && { echo "Error: --target required" >&2; exit 1; }

AGENTS_MD="$TARGET/AGENTS.md"
ERRORS=0
WARNINGS=0

fail()    { echo "  [FAIL] $*" >&2; ((ERRORS++));   }
warn()    { echo "  [WARN] $*";     ((WARNINGS++)); }
ok()      { echo "  [ OK ] $*";                     }

echo "Validating: $AGENTS_MD"
echo ""

# ── Check file exists ─────────────────────────────────────────────────────────
if [[ ! -f "$AGENTS_MD" ]]; then
  fail "AGENTS.md not found at $AGENTS_MD"
  echo ""
  echo "Validation failed: $ERRORS error(s)"
  exit 1
fi

# ── Check file is non-empty ───────────────────────────────────────────────────
WORD_COUNT=$(wc -w < "$AGENTS_MD")
if [[ "$WORD_COUNT" -lt 50 ]]; then
  fail "AGENTS.md is suspiciously small ($WORD_COUNT words). Was composition successful?"
else
  ok "File size ($WORD_COUNT words)"
fi

# ── Check no unfilled template tokens remain ──────────────────────────────────
TOKENS=$(grep -oE '\{\{[A-Z_]+\}\}' "$AGENTS_MD" | sort -u || true)
if [[ -n "$TOKENS" ]]; then
  fail "Unfilled template tokens found: $TOKENS"
else
  ok "No unfilled template tokens"
fi

# ── Check for auto-gen header ─────────────────────────────────────────────────
if grep -q "AUTO-GENERATED by agentic library" "$AGENTS_MD"; then
  ok "Auto-generated header present"
else
  warn "Auto-generated header not found — was this file manually created?"
fi

# ── Check lock file exists ────────────────────────────────────────────────────
LOCK_FILE="$TARGET/.agentic/config.yaml"
if [[ -f "$LOCK_FILE" ]]; then
  ok "Lock file present: .agentic/config.yaml"

  # ── Check tier AGENTS.md files for nested mode ──────────────────────────────
  nested_structure=$(yq '.structure // "flat"' "$LOCK_FILE" 2>/dev/null || echo "flat")
  if [[ "$nested_structure" == "nested" ]]; then
    while IFS= read -r tier; do
      [[ -z "$tier" || "$tier" == "null" ]] && continue
      if [[ -f "$TARGET/$tier/AGENTS.md" ]]; then
        ok "Tier AGENTS.md present: ${tier}/AGENTS.md"
      else
        fail "Tier AGENTS.md missing: ${tier}/AGENTS.md (run 'just compose' to regenerate)"
      fi
    done < <(yq '.tiers[]' "$LOCK_FILE" 2>/dev/null || true)
  fi
else
  warn "Lock file missing (.agentic/config.yaml) — run 'just compose' to generate it"
fi

# ── Check at least one H2 section is present ─────────────────────────────────
SECTION_COUNT=$(grep -c '^## ' "$AGENTS_MD" || true)
if [[ "$SECTION_COUNT" -lt 2 ]]; then
  fail "Too few sections found ($SECTION_COUNT). Expected at least 2 H2 sections."
else
  ok "Sections found: $SECTION_COUNT"
fi

# ── Report ────────────────────────────────────────────────────────────────────
echo ""
if [[ "$ERRORS" -gt 0 ]]; then
  echo "Validation FAILED: $ERRORS error(s), $WARNINGS warning(s)"
  exit 1
elif [[ "$WARNINGS" -gt 0 ]]; then
  echo "Validation PASSED with $WARNINGS warning(s)"
else
  echo "Validation PASSED"
fi
