#!/usr/bin/env bash
# vendor-gen.sh — Generates vendor-specific files from a target project's AGENTS.md
# Called by: just vendor-gen <target> [vendors]
set -euo pipefail

# Source common utilities
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=tooling/lib/common.sh
source "$SCRIPT_DIR/common.sh"

# ── Argument parsing ──────────────────────────────────────────────────────────
LIBRARY=""
TARGET=""
VENDORS="all"
LINK_MODE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --library) require_arg "--library" "$2"; LIBRARY="$2"; shift 2 ;;
    --target)  require_arg "--target" "$2";  TARGET="$2";  shift 2 ;;
    --vendors) require_arg "--vendors" "$2"; VENDORS="$2"; shift 2 ;;
    --link)    LINK_MODE=true; shift ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

[[ -z "$LIBRARY" ]] && { echo "Error: --library required" >&2; exit 1; }
[[ -z "$TARGET"  ]] && { echo "Error: --target required" >&2; exit 1; }

AGENTS_MD="$TARGET/AGENTS.md"
[[ ! -f "$AGENTS_MD" ]] && {
  echo "Error: $AGENTS_MD not found. Run 'just compose' first." >&2
  exit 1
}

LOCK_FILE="$TARGET/.agentic/config.yaml"
GENERATED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
PROJECT_NAME=$(basename "$TARGET")
PROFILE="unknown"
PROFILE_VER="unknown"
COMPOSE_MODE="lean"
[[ -f "$LOCK_FILE" ]] && {
  PROFILE=$(yq '.profile'             "$LOCK_FILE" 2>/dev/null || echo "unknown")
  PROFILE_VER=$(yq '.profile_version' "$LOCK_FILE" 2>/dev/null || echo "unknown")
  COMPOSE_MODE=$(yq '.mode // "lean"' "$LOCK_FILE" 2>/dev/null || echo "lean")
}

FRAGS_DIR="$TARGET/.agentic/fragments"
VENDOR_FILES_DIR="$TARGET/.agentic/vendor-files"

# ── Resolve which vendors to generate ─────────────────────────────────────────
resolve_vendors() {
  if [[ "$VENDORS" == "all" ]]; then
    echo "${AGENTIC_VENDORS[*]}"
  else
    echo "${VENDORS//,/ }"
  fi
}

# ── Section extraction ────────────────────────────────────────────────────────
# Escape special regex characters in a string
escape_regex() {
  local input="$1"
  local sed_pattern
  sed_pattern="s/[].[\\*^\\$()/]/\\\\&/g"
  local escaped
  escaped=$(printf "%s" "$input" | sed "$sed_pattern")
  printf "%s" "$escaped"
}

# Extract a section from a monolithic AGENTS.md by its H2 heading (full mode)
extract_section() {
  local heading="$1"
  local file="$2"
  # Escape special regex characters in heading before using in awk pattern
  local escaped_heading
  escaped_heading=$(escape_regex "$heading")
  # Match from the heading line to the next H2 heading or end of file
  awk "/^## ${escaped_heading}/{found=1; next} found && /^## /{exit} found{print}" "$file"
}

# Extract a section from the fragments directory (lean mode)
# Finds the fragment file whose first H2 matches the heading, then returns its content
# minus the heading line itself (matching the behaviour of extract_section in full mode).
extract_section_from_fragments() {
  local heading="$1"   # e.g. "Git Conventions"
  local frags_dir="$2" # TARGET/.agentic/fragments/
  [[ ! -d "$frags_dir" ]] && return
  # Escape special regex characters in heading before using in pattern
  local escaped_heading
  escaped_heading=$(escape_regex "$heading")
  local match
  match=$(grep -rl "^## ${escaped_heading}$" "$frags_dir" 2>/dev/null | head -1)
  [[ -z "$match" ]] && return
  # Skip the first H2 heading line so callers get body content only,
  # matching the behaviour of extract_section which uses `next` to skip it.
  awk "/^## ${escaped_heading}/{found=1; next} found{print}" "$match"
}

# Unified dispatcher: routes to the right source depending on compose mode
get_section_content() {
  local heading="$1"  # heading text without "## " prefix, e.g. "Git Conventions"
  if [[ "$COMPOSE_MODE" == "lean" ]]; then
    extract_section_from_fragments "$heading" "$FRAGS_DIR"
  else
    extract_section "$heading" "$AGENTS_MD"
  fi
}

# ── Auto-gen header ───────────────────────────────────────────────────────────
autogen_header() {
  cat <<HDR
<!-- AUTO-GENERATED by agentic library -->
<!-- Source profile: ${PROFILE} (v${PROFILE_VER}) -->
<!-- Generated: ${GENERATED_AT} -->
<!-- DO NOT EDIT — regenerate with: just vendor-gen ${TARGET} -->

HDR
}

# ── Vendor script loader ─────────────────────────────────────────────────────────
load_vendor_script() {
  local vendor="$1"
  local script_path="$SCRIPT_DIR/vendors/${vendor}.sh"
  if [[ -f "$script_path" ]]; then
    # shellcheck source=tooling/lib/vendors/claude.sh
    source "$script_path"
  else
    echo "Warning: vendor script not found: $script_path" >&2
  fi
}

# Load all vendor scripts
# shellcheck source=tooling/lib/vendors/claude.sh
source "$SCRIPT_DIR/vendors/claude.sh"
# shellcheck source=tooling/lib/vendors/copilot.sh
source "$SCRIPT_DIR/vendors/copilot.sh"
# shellcheck source=tooling/lib/vendors/codex.sh
source "$SCRIPT_DIR/vendors/codex.sh"
# shellcheck source=tooling/lib/vendors/gemini.sh
source "$SCRIPT_DIR/vendors/gemini.sh"
# shellcheck source=tooling/lib/vendors/opencode.sh
source "$SCRIPT_DIR/vendors/opencode.sh"

# ── Main ──────────────────────────────────────────────────────────────────────
mkdir -p "$VENDOR_FILES_DIR"

for vendor in $(resolve_vendors); do
  echo "Generating vendor files: $vendor"
  case "$vendor" in
    claude)   gen_claude   ;;
    copilot)  gen_copilot  ;;
    codex)    gen_codex    ;;
    gemini)   gen_gemini   ;;
    opencode) gen_opencode ;;
    *) echo "Warning: unknown vendor '$vendor' — skipping" >&2 ;;
  esac
done

echo ""
echo "Vendor files generated in: $TARGET/.agentic/vendor-files/"

# ── Link mode: move generated files to library _generated dir and symlink ───
if [[ "$LINK_MODE" == "true" ]]; then
  PROJECT_NAME=$(basename "$TARGET")
  GENERATED_DIR="$LIBRARY/_generated/$PROJECT_NAME/vendor-files"
  mkdir -p "$GENERATED_DIR"
  cp -r "$VENDOR_FILES_DIR/." "$GENERATED_DIR/"
  safe_rm_rf "$VENDOR_FILES_DIR"
  ln -sf "$GENERATED_DIR" "$VENDOR_FILES_DIR"
  echo "Linked .agentic/vendor-files → $GENERATED_DIR (link mode)"
fi
