#!/bin/bash
# vendor-gen.sh — Generates vendor-specific files from a target project's AGENTS.md
# Called by: just vendor-gen <target> [vendors]
set -euo pipefail

# ── Argument parsing ──────────────────────────────────────────────────────────
LIBRARY=""
TARGET=""
VENDORS="all"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --library) LIBRARY="$2"; shift 2 ;;
    --target)  TARGET="$2";  shift 2 ;;
    --vendors) VENDORS="$2"; shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

[[ -z "$LIBRARY" ]] && { echo "Error: --library required" >&2; exit 1; }
[[ -z "$TARGET"  ]] && { echo "Error: --target required" >&2; exit 1; }

AGENTS_MD="$TARGET/AGENTS.md"
[[ ! -f "$AGENTS_MD" ]] && {
  echo "Error: $AGENTS_MD not found. Run 'just compose' first." >&2
  exit 1
}

LOCK_FILE="$TARGET/.agentic/config.yaml"
GENERATED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
PROJECT_NAME=$(basename "$TARGET")
PROFILE="unknown"
PROFILE_VER="unknown"
[[ -f "$LOCK_FILE" ]] && {
  PROFILE=$(yq '.profile'         "$LOCK_FILE" 2>/dev/null || echo "unknown")
  PROFILE_VER=$(yq '.profile_version' "$LOCK_FILE" 2>/dev/null || echo "unknown")
}

# ── Resolve which vendors to generate ─────────────────────────────────────────
resolve_vendors() {
  if [[ "$VENDORS" == "all" ]]; then
    echo "claude copilot codex gemini opencode"
  else
    echo "${VENDORS//,/ }"
  fi
}

# ── Section extraction ────────────────────────────────────────────────────────
# Extract a section from AGENTS.md by its H2 heading
extract_section() {
  local heading="$1"
  local file="$2"
  # Match from the heading line to the next H2 heading or end of file
  awk "/^## ${heading//\//\\/}/{found=1; next} found && /^## /{exit} found{print}" "$file"
}

# ── Auto-gen header ───────────────────────────────────────────────────────────
autogen_header() {
  cat <<HDR
<!-- AUTO-GENERATED by agentic library -->
<!-- Source profile: ${PROFILE} (v${PROFILE_VER}) -->
<!-- Generated: ${GENERATED_AT} -->
<!-- DO NOT EDIT — regenerate with: just vendor-gen ${TARGET} -->

HDR
}

# ── Claude adapter ────────────────────────────────────────────────────────────
gen_claude() {
  echo "  Generating Claude adapter..."
  local template="$LIBRARY/vendors/claude/template.CLAUDE.md"
  local out_file="$TARGET/CLAUDE.md"

  sed \
    -e "s/{{PROJECT_NAME}}/${PROJECT_NAME}/g" \
    -e "s/{{PROFILE_NAME}}/${PROFILE}/g" \
    -e "s/{{PROFILE_VERSION}}/${PROFILE_VER}/g" \
    -e "s/{{GENERATED_AT}}/${GENERATED_AT}/g" \
    -e "s|{{TARGET_PATH}}|${TARGET}|g" \
    "$template" > "$out_file"

  echo "  Created: CLAUDE.md"
}

# ── Copilot adapter ───────────────────────────────────────────────────────────
gen_copilot() {
  echo "  Generating Copilot adapter..."
  local adapter="$LIBRARY/vendors/copilot/adapter.json"
  local instructions_dir="$TARGET/.github/instructions"
  local global_file="$TARGET/.github/copilot-instructions.md"

  mkdir -p "$TARGET/.github" "$instructions_dir"

  # Global instructions file (all always-on sections concatenated)
  {
    autogen_header
    echo "# GitHub Copilot Instructions — ${PROJECT_NAME}"
    echo ""
    # Extract always-on sections by reading adapter mappings
    jq -r '.section_mappings[] | select(.activation_mode == "always-on") | .agents_md_heading' "$adapter" | \
    sed 's/^## //' | while read -r heading; do
      content=$(extract_section "$heading" "$AGENTS_MD")
      [[ -n "$content" ]] && printf '\n## %s\n\n%s\n' "$heading" "$content"
    done
  } > "$global_file"
  echo "  Created: .github/copilot-instructions.md"

  # Per-language scoped instruction files
  jq -r '.section_mappings[] | select(.activation_mode == "glob-scoped") | [.agents_md_heading, .output_file, (.frontmatter.applyTo // "")] | @tsv' "$adapter" | \
  while IFS=$'\t' read -r heading out_file glob; do
    heading_text="${heading#\## }"
    content=$(extract_section "$heading_text" "$AGENTS_MD")
    [[ -z "$content" ]] && continue

    out_path="$TARGET/.github/$out_file"
    mkdir -p "$(dirname "$out_path")"
    {
      echo "---"
      echo "applyTo: \"${glob}\""
      echo "---"
      echo ""
      autogen_header
      printf '## %s\n\n%s\n' "$heading_text" "$content"
    } > "$out_path"
    echo "  Created: .github/$out_file"
  done
}

# ── Codex adapter ─────────────────────────────────────────────────────────────
gen_codex() {
  echo "  Generating Codex adapter (passthrough — AGENTS.md is native)..."
  # Codex reads AGENTS.md natively. No transformation needed.
  echo "  AGENTS.md is already the Codex-compatible file."
}

# ── Gemini adapter ────────────────────────────────────────────────────────────
gen_gemini() {
  echo "  Generating Gemini adapter..."
  local template="$LIBRARY/vendors/gemini/template.systemPrompt.md"
  local gemini_dir="$TARGET/.gemini"
  local out_file="$gemini_dir/systemPrompt.md"

  mkdir -p "$gemini_dir"

  # Concatenate all sections into the system prompt
  ALL_SECTIONS=$(awk '/^## /{found=1} found{print}' "$AGENTS_MD")

  sed \
    -e "s/{{PROJECT_NAME}}/${PROJECT_NAME}/g" \
    -e "s/{{PROFILE_NAME}}/${PROFILE}/g" \
    -e "s/{{PROFILE_VERSION}}/${PROFILE_VER}/g" \
    -e "s/{{GENERATED_AT}}/${GENERATED_AT}/g" \
    -e "s|{{TARGET_PATH}}|${TARGET}|g" \
    "$template" | sed "s|{{ALL_SECTIONS}}||" > "$out_file"

  # Append sections after the template header
  echo "" >> "$out_file"
  echo "$ALL_SECTIONS" >> "$out_file"

  echo "  Created: .gemini/systemPrompt.md"
}

# ── Opencode adapter ──────────────────────────────────────────────────────────
gen_opencode() {
  echo "  Generating Opencode adapter..."
  local template="$LIBRARY/vendors/opencode/template.opencode.json"
  local out_file="$TARGET/opencode.json"

  sed \
    -e "s/{{PROJECT_NAME}}/${PROJECT_NAME}/g" \
    -e "s/{{PROFILE_NAME}}/${PROFILE}/g" \
    -e "s/{{PROFILE_VERSION}}/${PROFILE_VER}/g" \
    -e "s/{{GENERATED_AT}}/${GENERATED_AT}/g" \
    -e "s|{{TARGET_PATH}}|${TARGET}|g" \
    "$template" > "$out_file"

  echo "  Created: opencode.json"
  echo "  Opencode reads AGENTS.md natively — AGENTS.md is already the Opencode-compatible file."
}

# ── Main ──────────────────────────────────────────────────────────────────────
for vendor in $(resolve_vendors); do
  echo "Generating vendor files: $vendor"
  case "$vendor" in
    claude)   gen_claude   ;;
    copilot)  gen_copilot  ;;
    codex)    gen_codex    ;;
    gemini)   gen_gemini   ;;
    opencode) gen_opencode ;;
    *) echo "Warning: unknown vendor '$vendor' — skipping" >&2 ;;
  esac
done

echo ""
echo "Vendor files generated in: $TARGET"
